### ISSUE TITLE
Block generation fails

### ISSUE THREAD

**Issue by caleteeter** [Consensys-Incorporated/quorum#160]
After running a Quorum network (deployed from Azure template), I am getting exceptions on the blockmaker.  This network (1 blockmaker and 1 voter) has been running for a few weeks, not under massive load (just developers).

WARN 2017-07-23 11:06:01,812 [BlockSaver-34] (SqlExceptionHelper.java:129) SQL Error: 3403, SQLState: 22003
ERROR 2017-07-23 11:06:01,813 [BlockSaver-34] (SqlExceptionHelper.java:131) data exception: numeric value out of range;  table: BLOCKS column: TOTALDIFFICULTY
ERROR 2017-07-23 11:06:01,813 [BlockSaver-34] (BatchingBatch.java:124) HHH000315: Exception executing batch [could not execute batch]
ERROR 2017-07-23 11:06:01,813 [BlockSaver-34] (SessionImpl.java:3166) HHH000346: Error during managed flush [could not execute batch]
ERROR 2017-07-23 11:06:01,842 [BlockSaver-34] (SavingBlockListener.java:53 ) BlockSaverThread died
org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into PUBLIC.BLOCKS (difficulty, extraData, gasLimit, gasUsed, logsBloom, miner, nonce, block_number, parentId, sha3Uncles, stateRoot, timestamp_val, totalDifficulty, transactionsRoot, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not execute batch
        at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:168)
        at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:741)
        at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:589)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at com.jpmorgan.cakeshop.dao.BlockDAO$$EnhancerBySpringCGLIB$$6304e8b.save(<generated>)
        at com.jpmorgan.cakeshop.db.SavingBlockListener.saveBlock(SavingBlockListener.java:108)
        at com.jpmorgan.cakeshop.db.SavingBlockListener$BlockSaverThread.run(SavingBlockListener.java:48)
Caused by: org.hibernate.exception.DataException: could not execute batch
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:118)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:119)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:97)
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:147)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:214)
        at org.hibernate.engine.spi.ActionQueue.ex^C

**Comment by caleteeter** [comment]
Moving this to Cakeshop, as after some looking it appears to be coming from a cs instance on the bm.
