### ISSUE TITLE
Quorum behind a proxy

### ISSUE THREAD

**Issue by jlgarciasan** [Consensys-Incorporated/quorum#200]
#### System information

Geth version: 1.5.0-unstable-647025ed

OS & Version: Ubuntu 16.04

Branch, Commit Hash or Release: Quorum 1.2..0 Constellation 0.1.0

#### Expected behaviour
We are trying to connect to external nodes that are out of our organization, and we need to expose the machine in which we have installed Quorum and Constellation behind a proxy.

When Quorum and constellation start, it must be connected to the external nodes. These nodes has our public ip in their whitelist. All the ports that are neccesary are opened.

#### Actual behaviour
At this moment when Quorum start behind a proxy launch the following error:

````
raft2017/10/20 15:23:18 tocommit(5) is out of range [lastIndex(4)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(5) is out of range [lastIndex(4)]. Was the raft log corrupted, truncated, or lost?
````
#### Backtrace

````
raft2017/10/20 15:23:18 INFO: 3 [term: 1] received a MsgHeartbeat message with higher term from 4 [term: 2]
raft2017/10/20 15:23:18 INFO: 3 became follower at term 2
raft2017/10/20 15:23:18 tocommit(5) is out of range [lastIndex(4)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(5) is out of range [lastIndex(4)]. Was the raft log corrupted, truncated, or lost?

goroutine 100 [running]:
log.(*Logger).Panicf(0xc420206870, 0xef1aef, 0x5d, 0xc4217e3b00, 0x2, 0x2)
        /usr/local/go/src/log/log.go:215 +0xdb
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x17ed720, 0xef1aef, 0x5d, 0xc4217e3b00, 0x2, 0x2)
        /home/user1/proxy-voting/binaries/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc42014b110, 0x5)
        /home/user1/proxy-voting/binaries/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/log.go:191 +0x15c
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc4201005a0, 0x8, 0x3, 0x4, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/user1/proxy-voting/binaries/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:1095 +0x54
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.stepFollower(0xc4201005a0, 0x8, 0x3, 0x4, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/user1/proxy-voting/binaries/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:1041 +0x2b3
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc4201005a0, 0x8, 0x3, 0x4, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/user1/proxy-voting/binaries/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:778 +0x10f7
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*node).run(0xc42014b1f0, 0xc4201005a0)
        /home/user1/proxy-voting/binaries/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/node.go:346 +0x728
created by github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.StartNode
        /home/user1/proxy-voting/binaries/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/node.go:215 +0x48e
````

**Comment by shikharka** [comment]
Hello, 

I am facing the same issue.
Not sure how to fix this

**Comment by fixanoid** [comment]
> Hello,
> 
> I am facing the same issue.
> Not sure how to fix this

Please do not reply on closed issues and instead, open a new one describing the problem you have encountered. Thanks.
