### ISSUE TITLE
Panic when trying to deploy a contract with Istanbul

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#215]
Following setup:
- istanbul with 2 nodes
- forgot to allocate any ether
- attempt to deploy contract using the key of one of the validators

```
ERROR[11-07|07:08:54] goroutine 8493 [running]:
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func1(0xc420d36700, 0x1938600, 0xc42340bc70)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:135 +0x12d
panic(0xefa380, 0xc420012090)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/ethereum/go-ethereum/miner.(*worker).pending(0xc4200803c0, 0x0, 0x0, 0x0)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:191 +0x1c2
github.com/ethereum/go-ethereum/miner.(*Miner).Pending(0xc420416690, 0x42bfef, 0x19ffa60, 0x1933940)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/miner.go:168 +0x2f
github.com/ethereum/go-ethereum/eth.(*EthApiBackend).StateAndHeaderByNumber(0xc420012b40, 0x1933940, 0xc422985180, 0xfffffffffffffffe, 0x42dcc9, 0xf26aa0, 0xf5ec60, 0xc422985180, 0xc42340bd18)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/api_backend.go:103 +0x1f2
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).GetTransactionCount(0xc420ccc260, 0x1933940, 0xc422985180, 0x85e96a14e08ce1c2, 0xc81a46c40fdf6d09, 0xee2de8b, 0xfffffffffffffffe, 0x0, 0x0, 0x0)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:961 +0x5e
reflect.Value.call(0xc420212600, 0xc420027420, 0x13, 0x103709e, 0x4, 0xc4231f1f20, 0x4, 0x4, 0x2, 0xf5ec60, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc420212600, 0xc420027420, 0x13, 0xc4231f1f20, 0x4, 0x4, 0x2, 0x2, 0x11e2911)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc420d36700, 0x1933940, 0xc422985180, 0x1938600, 0xc42340bc70, 0xc4231f1ec0, 0xc42340bce0, 0x0, 0xebc5e0)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:311 +0x8ea
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc420d36700, 0x1933940, 0xc422985180, 0x1938600, 0xc42340bc70, 0xc4231f1ec0)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:333 +0x1d9
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc420d36700, 0x1938600, 0xc42340bc70, 0xc420db7b01, 0x1, 0x0, 0x0)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:194 +0x414
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc420d36700, 0x1938600, 0xc42340bc70, 0x1)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:225 +0x4e
github.com/ethereum/go-ethereum/rpc.(*Server).ServeHTTP(0xc420d36700, 0x1932380, 0xc423d48750, 0xc423d45770)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:161 +0x4f4
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1932380, 0xc423d48750, 0xc423d45770)
	/home/ec2-user/gowork/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rs/cors/cors.go:190 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc420d37fe0, 0x1932380, 0xc423d48750, 0xc423d45770)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420d5ee80, 0x1932380, 0xc423d48750, 0xc423d45770)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4229b5080, 0x1933940, 0xc4229850c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by markya0616** [comment]
According to the logs, it crashes while to get pending block. https://github.com/jpmorganchase/quorum/blob/master/miner/worker.go#L191. However, we cannot reproduce the issue in our side. Can you provide more logs or more details? Thanks.

**Comment by stevenroose** [comment]
Our build was at commit `6a6b52c6cc1f4e1057f2a0741c69bd88cbe2801a`, are you on the same one? 

To me it seems that this error could not be very dependent on our specific setup.

**Comment by stevenroose** [comment]
This is the diff with current Quorum master:
```diff
diff --git a/README.md b/README.md
index 6cd0be8ee..92e89c689 100644
--- a/README.md
+++ b/README.md
@@ -1,5 +1,7 @@
 # Quorum
 
+<a href="https://quorumslack.azurewebsites.net" target="_blank" rel="noopener"><img title="Quorum Slack" src="https://quorumslack.azurewebsites.net/badge.svg" alt="Quorum Slack" /></a>
+
 Quorum is an Ethereum-based distributed ledger protocol with transaction/contract privacy and new consensus mechanisms.
 
 Quorum is a fork of [go-ethereum](https://github.com/ethereum/go-ethereum) and is updated in line with go-ethereum releases.
diff --git a/cmd/geth/misccmd.go b/cmd/geth/misccmd.go
index 7e15a9ad7..63c02438f 100644
--- a/cmd/geth/misccmd.go
+++ b/cmd/geth/misccmd.go
@@ -112,6 +112,7 @@ func version(ctx *cli.Context) error {
 	if gitCommit != "" {
 		fmt.Println("Git Commit:", gitCommit)
 	}
+	fmt.Println("Quorum Version:", params.QuorumVersion)
 	fmt.Println("Architecture:", runtime.GOARCH)
 	fmt.Println("Network Id:", eth.DefaultConfig.NetworkId)
 	fmt.Println("Go Version:", runtime.Version())
diff --git a/core/vm/gas_table.go b/core/vm/gas_table.go
index 0d8e295a5..7b9efdfc8 100644
--- a/core/vm/gas_table.go
+++ b/core/vm/gas_table.go
@@ -119,8 +119,9 @@ func gasReturnDataCopy(gt params.GasTable, evm *EVM, contract *Contract, stack *
 
 func gasSStore(gt params.GasTable, evm *EVM, contract *Contract, stack *Stack, mem *Memory, memorySize uint64) (uint64, error) {
 	var (
+		db   = getDualState(evm, contract.Address())
 		y, x = stack.Back(1), stack.Back(0)
-		val  = evm.StateDB.GetState(contract.Address(), common.BigToHash(x))
+		val  = db.GetState(contract.Address(), common.BigToHash(x))
 	)
 	// This checks for 3 scenario's and calculates gas accordingly
 	// 1. From a zero-value address to a non-zero value         (NEW VALUE)
@@ -130,7 +131,7 @@ func gasSStore(gt params.GasTable, evm *EVM, contract *Contract, stack *Stack, m
 		// 0 => non 0
 		return params.SstoreSetGas, nil
 	} else if !common.EmptyHash(val) && common.EmptyHash(common.BigToHash(y)) {
-		evm.StateDB.AddRefund(new(big.Int).SetUint64(params.SstoreRefundGas))
+		db.AddRefund(new(big.Int).SetUint64(params.SstoreRefundGas))
 
 		return params.SstoreClearGas, nil
 	} else {
@@ -324,10 +325,10 @@ func gasCall(gt params.GasTable, evm *EVM, contract *Contract, stack *Stack, mem
 		eip158         = evm.ChainConfig().IsEIP158(evm.BlockNumber)
 	)
 	if eip158 {
-		if transfersValue && evm.StateDB.Empty(address) {
+		if transfersValue && getDualState(evm, address).Empty(address) {
 			gas += params.CallNewAccountGas
 		}
-	} else if !evm.StateDB.Exist(address) {
+	} else if !getDualState(evm, address).Exist(address) {
 		gas += params.CallNewAccountGas
 	}
 	if transfersValue {
@@ -401,6 +402,7 @@ func gasRevert(gt params.GasTable, evm *EVM, contract *Contract, stack *Stack, m
 }
 
 func gasSuicide(gt params.GasTable, evm *EVM, contract *Contract, stack *Stack, mem *Memory, memorySize uint64) (uint64, error) {
+	var db StateDB
 	var gas uint64
 	// EIP150 homestead gas reprice fork:
 	if evm.ChainConfig().IsEIP150(evm.BlockNumber) {
@@ -409,19 +411,20 @@ func gasSuicide(gt params.GasTable, evm *EVM, contract *Contract, stack *Stack,
 			address = common.BigToAddress(stack.Back(0))
 			eip158  = evm.ChainConfig().IsEIP158(evm.BlockNumber)
 		)
+		db = getDualState(evm, address)
 
 		if eip158 {
 			// if empty and transfers value
-			if evm.StateDB.Empty(address) && evm.StateDB.GetBalance(contract.Address()).Sign() != 0 {
+			if db.Empty(address) && db.GetBalance(contract.Address()).Sign() != 0 {
 				gas += gt.CreateBySuicide
 			}
-		} else if !evm.StateDB.Exist(address) {
+		} else if !db.Exist(address) {
 			gas += gt.CreateBySuicide
 		}
 	}
 
-	if !evm.StateDB.HasSuicided(contract.Address()) {
-		evm.StateDB.AddRefund(new(big.Int).SetUint64(params.SuicideRefundGas))
+	if !db.HasSuicided(contract.Address()) {
+		db.AddRefund(new(big.Int).SetUint64(params.SuicideRefundGas))
 	}
 	return gas, nil
 }
diff --git a/core/vm/instructions.go b/core/vm/instructions.go
index b6d6e22c4..1d320680d 100644
--- a/core/vm/instructions.go
+++ b/core/vm/instructions.go
@@ -324,7 +324,7 @@ func opAddress(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *
 
 func opBalance(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *Stack) ([]byte, error) {
 	addr := common.BigToAddress(stack.pop())
-	balance := evm.StateDB.GetBalance(addr)
+	balance := getDualState(evm, addr).GetBalance(addr)
 
 	stack.push(new(big.Int).Set(balance))
 	return nil, nil
@@ -393,7 +393,7 @@ func opExtCodeSize(pc *uint64, evm *EVM, contract *Contract, memory *Memory, sta
 	a := stack.pop()
 
 	addr := common.BigToAddress(a)
-	a.SetInt64(int64(evm.StateDB.GetCodeSize(addr)))
+	a.SetInt64(int64(getDualState(evm, addr).GetCodeSize(addr)))
 	stack.push(a)
 
 	return nil, nil
@@ -425,7 +425,7 @@ func opExtCodeCopy(pc *uint64, evm *EVM, contract *Contract, memory *Memory, sta
 		codeOffset = stack.pop()
 		length     = stack.pop()
 	)
-	codeCopy := getDataBig(evm.StateDB.GetCode(addr), codeOffset, length)
+	codeCopy := getDataBig(getDualState(evm, addr).GetCode(addr), codeOffset, length)
 	memory.Set(memOffset.Uint64(), length.Uint64(), codeCopy)
 
 	evm.interpreter.intPool.put(memOffset, codeOffset, length)
@@ -508,7 +508,7 @@ func opMstore8(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *
 
 func opSload(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *Stack) ([]byte, error) {
 	loc := common.BigToHash(stack.pop())
-	val := evm.StateDB.GetState(contract.Address(), loc).Big()
+	val := getDualState(evm, contract.Address()).GetState(contract.Address(), loc).Big()
 	stack.push(val)
 	return nil, nil
 }
@@ -516,7 +516,7 @@ func opSload(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *St
 func opSstore(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *Stack) ([]byte, error) {
 	loc := common.BigToHash(stack.pop())
 	val := stack.pop()
-	evm.StateDB.SetState(contract.Address(), loc, common.BigToHash(val))
+	getDualState(evm, contract.Address()).SetState(contract.Address(), loc, common.BigToHash(val))
 
 	evm.interpreter.intPool.put(val)
 	return nil, nil
@@ -741,10 +741,11 @@ func opStop(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *Sta
 }
 
 func opSuicide(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *Stack) ([]byte, error) {
-	balance := evm.StateDB.GetBalance(contract.Address())
-	evm.StateDB.AddBalance(common.BigToAddress(stack.pop()), balance)
+	db := getDualState(evm, contract.Address())
+	balance := db.GetBalance(contract.Address())
+	db.AddBalance(common.BigToAddress(stack.pop()), balance)
 
-	evm.StateDB.Suicide(contract.Address())
+	db.Suicide(contract.Address())
 	return nil, nil
 }
 
diff --git a/params/version.go b/params/version.go
index 907b9ddc1..8d0e526cf 100644
--- a/params/version.go
+++ b/params/version.go
@@ -38,11 +38,14 @@ var Version = func() string {
 		v += "-" + VersionMeta
 	}
 
-	v = fmt.Sprintf("quorum %d.%d.%d (geth %s)", QuorumVersionMajor, QuorumVersionMinor, QuorumVersionPatch, v)
-
 	return v
 }()
 
+// Version holds the textual version string.
+var QuorumVersion = func() string {
+	return fmt.Sprintf("%d.%d.%d", QuorumVersionMajor, QuorumVersionMinor, QuorumVersionPatch)
+}()
+
 func VersionWithCommit(gitCommit string) string {
 	vsn := Version
 	if len(gitCommit) >= 8 {
```

**Comment by markya0616** [comment]
I tried `6a6b52c6cc1f4e1057f2a0741c69bd88cbe2801a`, and it also works for me. Can you share your setup procedure step by step? like the genesis file, the private key (node key) of two validators, the commands to start quorum, and how to deploy the contract, etc. I will try to re-produce it in my side.

**Comment by markya0616** [comment]
Sorry, I still cannot re-produce it in my side. Share my config:
1. genesis file:
```
{
  "config": {
    "chainId": 1234,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "istanbul": {
      "epoch": 30000,
      "policy": 0
    },
    "isQuorum": true
  },
  "alloc": {},
  "nonce": "0x0",
  "timestamp": "0x5982d805",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f86fea941cd6d479eda90f876366c32a7932eaf7116aa39394294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

2. nodekey

`487ab5019b652562b9b3a2dfee5b757d211a00e533339d30a54bf6fee8b7810a`
`72fa6fc77e8ea98a5adc168c0ceed63205d9580dcbb969df794248dee5a00ea5`

3. start geth

```
# $rpcport: rpc port
# $chaindir: data dir
# $port: local port
build/bin/geth --datadir "$chaindir" init "$chaindir/genesis.json"; build/bin/geth --identity "mchain_dev_local_1" --rpc --rpcport "$rpcport" --rpccorsdomain "*" --datadir "$chaindir" --port "$port" --nodiscover --rpcapi "db,istanbul,eth,net,web3,personal,debug,quorum" --networkid "20160816" --nat "any" --debug --gasprice 0 --mine --syncmode "full" console
```

4. create contract by "487ab5019b652562b9b3a2dfee5b757d211a00e533339d30a54bf6fee8b7810a", and then it works.

**Comment by stevenroose** [comment]
This is our genesis:
```json
{
  "config": {
    "chainId": 2016,
    "istanbul": {
		"epoch": 30000,
		"policy": 0
	}
  },
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x3500000000000000000000000000000000000000000000000000000000000000f86fea94c2e18ce0146ae985096ddf0fc4461ac88bdee20e949545bc3c9caf3912794f4ca4814485cb5c388e64b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0x47e7c4",
  "mixhash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase": "0x3333333333333333333333333333333333333333",
  "nonce": "0x0",
  "difficulty": "0x1",
  "alloc": {
    "0x9545bc3c9caf3912794f4ca4814485cb5c388e64": {
      "balance": "1000000000000000000000000000"
    },
    "0xc2e18ce0146ae985096ddf0fc4461ac88bdee20e": {
      "balance": "1000000000000000000000000000"
    }
  }
}
```

Node keys and private keys of the addresses in the genesis:
```
fe9f4bc6ede58ce1f544ae7e834ca53219e27051c54b86d11a1ddb453f9a48f6
444c1f549d18970133abde47c0f785aca75a5453eae7e381b884a3bf80bc32f6
```

I think the main difference is that we don't use web3 or the JS bindings to deploy contracts. We use the go bindings (go-ethereum/ethclient) and abigen. So I guess the calls would be different.

I was thinking with my colleague here that it might be useful to have some integration tests that use the Go bindings. Does Quorum have any? If not, we might be able to provide them.

**Comment by stevenroose** [comment]
F.e. the Go bindings use the API call to get the user nonce before making the actual deployment. Since that call gets the user nonce from the pending block, something tells me that it's that call that is making this panic.

**Comment by markya0616** [comment]
Your genesis.json needs to add `"isQuorum": true` into `config`, like below:
```
{
  "config": {
    "chainId": 2016,
    "istanbul": {
      "epoch": 30000,
      "policy": 0
    },
    "isQuorum": true
  },
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x3500000000000000000000000000000000000000000000000000000000000000f86fea94c2e18ce0146ae985096ddf0fc4461ac88bdee20e949545bc3c9caf3912794f4ca4814485cb5c388e64b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0x47e7c4",
  "mixhash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase": "0x3333333333333333333333333333333333333333",
  "nonce": "0x0",
  "difficulty": "0x1",
  "alloc": {
    "0x9545bc3c9caf3912794f4ca4814485cb5c388e64": {
      "balance": "1000000000000000000000000000"
    },
    "0xc2e18ce0146ae985096ddf0fc4461ac88bdee20e": {
      "balance": "1000000000000000000000000000"
    }
  }
}
```
After that, I use Go bindings to test, and contract deployment and sending transactions are OK! Incidentally, our team, AMIS, is also a fan of Go bindings. We have some tools which can speed up the DApp development by Go-binding and gRPC. If you're interested, you can refer our post, [gRPC in DApp Architecture](https://medium.com/getamis/grpc-in-dapp-architecture-8c34125356c7).

**Comment by stevenroose** [comment]
We have been using a genesis without `isQuorum` for as long as I can remember :) I will add it, but can it be the cause of the panic?

**Comment by joelburget** [comment]
I think it could be the cause of the panic.

`isQuorum` is new in 2.0. I added it to bring Quorum closer to vanilla Geth. Running without `isQuorum` (and Quorum-specific flags), it behaves exactly like vanilla Geth. This way we can run (and pass) all the Ethereum tests, ensuring that we haven't broken anything. `git grep IsQuorum` shows 26 results -- places where we check the chain config to see whether we're running as Quorum or not, and branching accordingly. This is extremely helpful, at least for me, to isolate what exactly Quorum does.

So, if you're accessing private state without `IsQuorum` set, the private state may be nil, causing this panic.

However, Quorum [tries to upgrade your genesis](https://github.com/jpmorganchase/quorum/blob/31f4acca56e79ee001f4b67110b9eea6dee336df/core/genesis.go#L194). I'm surprised that didn't happen. I'm interested to hear what happens when you run with it set.

**Comment by stevenroose** [comment]
Yes, that fixed it! Many thanks!

**Comment by pavradev** [comment]
@joelburget Could you explain how you set IsQuorum to 'false'? This property is not respected in my case and always set to 'true':
```
INFO [01-05|10:45:56] Initialised chain configuration          config="{ChainID: 1 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil> Byzantium: <nil> IsQuorum: true Engine: unknown}"
```
I took genesis.json from quorum-examles:
```
{
  "alloc": {
    "0xed9d02e382b34818e88b88a309c7fe71e65f419d": {
      "balance": "20000000000000000000"
    },
    "0x007ccffb7916f37f7aeef05e8096ecfbe55afc2f": {
      "balance": "20000000000000000000"
    },
    "0x99429f64cf4d5837620dcc293c1a537d58729b68": {
      "balance": "20000000000000000000"
    },
    "0xca247d7425a29c6645fa991f9151f994a830882d": {
      "balance": "20000000000000000000"
    },
    "0x794f74c8916310d6a0009bb8a43a5acab59a58ad": {
      "balance": "20000000000000000000"
    },
    "0x276ecb88715a503b00d1f15af4c17dc051991667": {
      "balance": "20000000000000000000"
    },
    "0x6b92a443BDB80EF0626f84450038371e9ae60757": {
      "balance": "20000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0,
    "chainId": 1,
    "eip155Block": null,
    "eip158Block": null,
    "isQuorum": false
  },
  "difficulty": "0x0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0xE0000000",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
```

**Comment by stevenroose** [comment]
@pavradev Your genesis file says `"isQuorum": false`. Change that to true.

**Comment by pavradev** [comment]
@stevenroose but I DO want it to be 'false' (for testing purposes), however it is always 'true' at runtime (see the log snippet). I've tried  setting `"isQuorum": false` and removing this parameter completely .. no luck

**Comment by stevenroose** [comment]
That's weird. Sounds like a separate bug. I'd open a new issue.
