### ISSUE TITLE
Unix socket timeout when deploying contract

### ISSUE THREAD

**Issue by MitchK** [Consensys-Incorporated/quorum#267]
I am trying to deploy a contract to a single-node setup, but I get a Unix socket timeout. Constellation and Geth are both running.

This is the startup log of Geth:
```
quorum_1  | INFO [01-25|22:30:07] Starting peer-to-peer node               instance=Geth/v1.7.2-stable/linux-amd64/go1.9.2
quorum_1  | INFO [01-25|22:30:07] Allocated cache and file handles         database=/qdata/dd/geth/chaindata cache=128 handles=1024
quorum_1  | INFO [01-25|22:30:07] Reconfiguring old genesis as Quorum
quorum_1  | INFO [01-25|22:30:07] Initialised chain configuration          config="{ChainID: <nil> Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil> Byzantium: <nil> IsQuorum: true Engine: unknown}"
quorum_1  | INFO [01-25|22:30:07] Disk storage enabled for ethash caches   dir=/qdata/dd/geth/ethash count=3
quorum_1  | INFO [01-25|22:30:07] Disk storage enabled for ethash DAGs     dir=/root/.ethash         count=2
quorum_1  | INFO [01-25|22:30:07] Initialising Ethereum protocol           versions="[63 62]" network=1
quorum_1  | INFO [01-25|22:30:07] Loaded most recent local header          number=0 hash=2a257a…e1016b td=0
quorum_1  | INFO [01-25|22:30:07] Loaded most recent local full block      number=0 hash=2a257a…e1016b td=0
quorum_1  | INFO [01-25|22:30:07] Loaded most recent local fast block      number=0 hash=2a257a…e1016b td=0
quorum_1  | INFO [01-25|22:30:07] Loaded local transaction journal         transactions=0 dropped=0
quorum_1  | INFO [01-25|22:30:07] Regenerated local transaction journal    transactions=0 accounts=0
quorum_1  | INFO [01-25|22:30:08] Starting P2P networking
quorum_1  | INFO [01-25|22:30:08] RLPx listener up                         self="enode://4641f0769fa3be170129d24e9a430ad54fa75835c467a520b588c831c71eda22d571ef92476cff7bd4070e43033edbd1f4d37091a86a62297aaa0e226fe9d27e@[::]:30303?discport=0"
quorum_1  | INFO [01-25|22:30:08] starting raft protocol handler
quorum_1  | INFO [01-25|22:30:08] loaded the latest applied index          lastAppliedIndex=11
quorum_1  | INFO [01-25|22:30:08] loading snapshot
quorum_1  | INFO [01-25|22:30:08] applying snapshot to raft storage
quorum_1  | INFO [01-25|22:30:08] updating cluster membership per raft snapshot
quorum_1  | INFO [01-25|22:30:08] updated cluster membership
quorum_1  | INFO [01-25|22:30:08] blockchain is caught up; no need to synchronize
quorum_1  | INFO [01-25|22:30:08] replaying WAL
quorum_1  | INFO [01-25|22:30:08] loading WAL                              term=0 index=0
quorum_1  | INFO [01-25|22:30:08] startRaft                                raft ID=1
quorum_1  | INFO [01-25|22:30:08] remounting an existing raft log; connecting to peers.
quorum_1  | raft2018/01/25 22:30:08 INFO: 1 became follower at term 11
quorum_1  | raft2018/01/25 22:30:08 INFO: newRaft 1 [peers: [1], term: 11, commit: 11, applied: 11, lastindex: 11, lastterm: 11]
quorum_1  | INFO [01-25|22:30:08] IPC endpoint opened: /qdata/dd/geth.ipc
quorum_1  | INFO [01-25|22:30:08] HTTP endpoint opened: http://0.0.0.0:8545
quorum_1  | INFO [01-25|22:30:08] Unlocked account                         address=0x7FD5719Cf15b81Bf0Fc78C4CC28F5E136740c9F8
quorum_1  | raft2018/01/25 22:30:09 INFO: 1 is starting a new election at term 11
quorum_1  | raft2018/01/25 22:30:09 INFO: 1 became candidate at term 12
quorum_1  | raft2018/01/25 22:30:09 INFO: 1 received MsgVoteResp from 1 at term 12
quorum_1  | raft2018/01/25 22:30:09 INFO: 1 became leader at term 12
quorum_1  | raft2018/01/25 22:30:09 INFO: raft.node: 1 elected leader 1 at term 12
quorum_1  | INFO [01-25|22:30:09] Not minting a new block since there are no pending transactions
quorum_1  | INFO [01-25|22:30:09] persisted the latest applied index       index=12
```

This is the code I am using:
```
a = web3.eth.accounts[0]
web3.eth.defaultAccount = a;

// abi and bytecode generated from simplestorage.sol:
// > solcjs --bin --abi simplestorage.sol
var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"payable":false,"type":"constructor"}];

var bytecode = "0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029";

var simpleContract = web3.eth.contract(abi);
var simple = simpleContract.new(42, {from:web3.eth.accounts[0], data: bytecode, gas: 0x47b760, privateFor: ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]}, function(e, contract) {
	if (e) {
		console.log("err creating contract", e);
	} else {
		if (!contract.address) {
			console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
		} else {
			console.log("Contract mined! Address: " + contract.address);
			console.log(contract);
		}
	}
});
```

#### System information

Geth version: 1.7.2 (Quorum 2.0.0) using Docker

Constellation version: 0.2.0

OS & Version: Ubuntu 16.04

#### Expected behaviour

It should deploy a simple contract correctly.

#### Actual behaviour

err creating contract Error: Post http+unix://c/send: read unix @->/qdata/tm.ipc: i/o timeout

#### Steps to reproduce the behaviour

I am using the following tm.conf:
```
url = "http://172.13.0.2:9000/"
port = 9000
socketPath = "/qdata/tm.ipc"
otherNodeUrls = ["http://172.13.0.2:9000/"]
publicKeyPath = "/qdata/keys/tm.pub"
privateKeyPath = "/qdata/keys/tm.key"
archivalPublicKeyPath = "/qdata/keys/tma.pub"
archivalPrivateKeyPath = "/qdata/keys/tma.key"
storagePath = "/qdata/constellation"
```

And these genesis block parameters:
```
{
  "alloc": {
    "7fd5719cf15b81bf0fc78c4cc28f5e136740c9f8": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0
  },
  "difficulty": "0x0",
  "extraData": "0x",
  "gasLimit": "0x2FEFD800",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
```

#### Backtrace

````
err creating contract Error: Post http+unix://c/send: read unix @->/qdata/tm.ipc: i/o timeout
    at Object.InvalidResponse (/scripts/js/node_modules/web3/lib/web3/errors.js:38:16)
    at /scripts/js/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/scripts/js/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/scripts/js/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/scripts/js/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/scripts/js/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/scripts/js/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
````

**Comment by MitchK** [comment]
Here is some more log information (from Constellation):
```
2018 Jan-25 22:51:47451583 [INFO] Log level is LevelDebug
2018 Jan-25 22:51:47452436 [DEBUG] Configuration: Config {cfgUrl = "http://172.13.0.2:9000/", cfgPort = 9000, cfgSocket = Just "/qdata/tm.ipc", cfgOtherNodes = ["http://172.13.0.2:9000/"], cfgPublicKeys = ["/qdata/keys/tm.pub","/qdata/keys/tma.pub"], cfgPrivateKeys = ["/qdata/keys/tm.key","/qdata/keys/tma.key"], cfgAlwaysSendTo = ["/qdata/keys/tma.pub"], cfgPasswords = Nothing, cfgStorage = "/qdata/constellation", cfgIpWhitelist = [], cfgJustShowVersion = False, cfgJustGenerateKeys = [], cfgVerbosity = 4}
2018 Jan-25 22:51:47453259 [INFO] Utilizing 4 core(s)
2018 Jan-25 22:51:47453945 [INFO] Constructing Enclave using keypairs [("/qdata/keys/tm.pub","/qdata/keys/tm.key"),("/qdata/keys/tma.pub","/qdata/keys/tma.key")]
2018 Jan-25 22:51:47466148 [INFO] Throwaway public key for self-sending: "gvMm4t62EmTce0WyKWgWdFb9AU37jtaVQDUZ7SnKllY="
2018 Jan-25 22:51:47466475 [INFO] Initializing storage /qdata/constellation
2018 Jan-25 22:51:48124797 [INFO] Internal API listening on /qdata/tm.ipc
2018 Jan-25 22:51:48124865 [INFO] Public API listening on 0.0.0.0 port 9000 with whitelist: ["Disabled"]
2018 Jan-25 22:51:48124700 [INFO] Node started
2018 Jan-25 22:51:57475065 [DEBUG] Request from : ApiUpcheck; Response: ApiUpcheckR
```

**Comment by patrickmn** [comment]
Is this happening after doing what we discussed in https://github.com/jpmorganchase/quorum/issues/252 or when running normally?

`url = "http://172.13.0.2:9000/"`
`otherNodeUrls = ["http://172.13.0.2:9000/"]`

`otherNodeUrls` should probably be empty here.

The `ROAZBW...` key is usually hosted by node 7. Is that node running in this example?

It would be helpful to have a fully reproducible (all config files) example of this if the above doesn't help.

**Comment by MitchK** [comment]
Hi @patrickmn.

This happens when running it normally (single node), not using your suggestion from the other post.
I removed ```otherNodeUrls``` completely and also tried setting it to ```[]```.

Yes, the key was from the example I used for demonstration. Actually, my script is more generic and I'm having the same issue.

**compileAndDeploy.js**
```
const Web3 = require('web3')
const solc = require('solc')
const minimist = require('minimist')
const fs = require('fs')


const argv = minimist(process.argv.slice(2))
if (!argv.solidityFile) {
	return console.error('No --solidityFile provided')
}
console.log('Reading file', argv.solidityFile, '...')
const sourceCode = fs.readFileSync(argv.solidityFile, 'utf-8')

console.log('Compiling Solidity code...')
const compiled = solc.compile(sourceCode, 1) // 1 activates optimiser
const root = compiled.contracts[Object.keys(compiled.contracts)[0]]

if (!argv.rpcEndpoint) {
	argv.rpcEndpoint = "http://localhost:8545"
}
const web3 = new Web3(new Web3.providers.HttpProvider(argv.rpcEndpoint))

const Contract = web3.eth.contract(JSON.parse(root.interface))

if (!argv.account) {
	argv.account = web3.eth.accounts[0]
}

var contractInstance = Contract.new(42, {
		from: argv.account,
		data: '0x' + root.bytecode,
		gas: 300000,
		privateFor: []
	},
	(err, contract) => {
	if (err) {
		console.error("err creating contract", err);
	} else {
		if (!contract.address) {
			console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
		} else {
			console.log("Contract mined! Address: " + contract.address);
			console.log(contract);
		}
	}
});
```

For compliance reasons, I can't share the full working project. I would need to build a shareable, reproducible prototype off it. In the mean time, I am trying to compare things with the example. If I continue hitting walls, I will build an executable example.

But this is basically my start up script that I run when I run my Docker container.

**start.sh**
```
#!/bin/bash


set -e

# Docker context, added via Dockerfile to container via "ADD . /root/context"
CONTEXT_PATH=/root/context

# We need this IP for various things in here
echo "*********** General ***********"
echo "---> Determining internal IP address from /etc/hosts file..."
INTERNAL_IP=${INTERNAL_IP:=$(awk 'END{print $1}' /etc/hosts)}
echo "INTERNAL_IP=${INTERNAL_IP}"

###########################################################
# Create tm.conf configuration from environment variables
###########################################################
echo "*********** Creating tm.conf ***********"

export QDATA_PATH=${QDATA_PATH:="/qdata"}
echo "QDATA_PATH=${QDATA_PATH}"

# Define defaults if environment variables not set
export TM_CONFIG_PORT=${TM_CONFIG_PORT:="9000"}
export TM_CONFIG_URL=${TM_CONFIG_URL:="http://172.13.0.2:${TM_CONFIG_PORT}/"}
export TM_CONFIG_SOCKET_PATH=${TM_CONFIG_SOCKET_PATH:="${QDATA_PATH}/tm.ipc"}
export TM_CONFIG_OTHER_NODE_URLS="[]" # ${TM_CONFIG_OTHER_NODE_URLS:="[\"${TM_CONFIG_URL}\"]"}
export TM_CONFIG_PUBLIC_KEY_PATH=${TM_CONFIG_PUBLIC_KEY_PATH:="${QDATA_PATH}/keys/tm.pub"}
export TM_CONFIG_PRIVATE_KEY_PATH=${TM_CONFIG_PRIVATE_KEY_PATH:="${QDATA_PATH}/keys/tm.key"}
export TM_CONFIG_ARCHIVAL_PUBLIC_KEY_PATH=${TM_CONFIG_ARCHIVAL_PUBLIC_KEY_PATH:="${QDATA_PATH}/keys/tma.pub"}
export TM_CONFIG_ARCHIVAL_PRIVATE_KEY_PATH=${TM_CONFIG_ARCHIVAL_PRIVATE_KEY_PATH:="${QDATA_PATH}/keys/tma.key"}
export TM_CONFIG_STORAGE_PATH=${TM_CONFIG_STORAGE_PATH="${QDATA_PATH}/constellation"}

# Show variable assignments
env | grep "TM_CONFIG_"

# Config file
TMCONF=${QDATA_PATH}/tm.conf

# Render template
envsubst < "${CONTEXT_PATH}/config/tm.conf.template" > "${TMCONF}"

#######################################################################
# Constellation setup
#######################################################################
echo "*********** Setting up constellation ***********"

mkdir -p "${QDATA_PATH}/keys"

# Create constellation private key if it doesnt exist
if [ ! -z "${QDATA_PATH}/keys/tm.key" ]; then
    echo "---> ${QDATA_PATH}/keys/tm.key doesnt exist, generating one..."
    constellation-node --generatekeys=${QDATA_PATH}/keys/tm < /dev/null > /dev/null # No password, no output
    echo "tm.pub=$(cat ${QDATA_PATH}/keys/tm.pub)"
else
    echo "---> ${QDATA_PATH}/keys/tm.key already exists, reusing..."
fi

# Create constellation archival private key if it doesnt exist
if [ ! -z "${QDATA_PATH}/keys/tma" ]; then
    echo "---> ${QDATA_PATH}/keys/tma.key doesnt exist, generating one..."
    constellation-node --generatekeys=${QDATA_PATH}/keys/tma < /dev/null > /dev/null # No password, no output
    echo "tma.pub=$(cat ${QDATA_PATH}/keys/tma.pub)"
else
    echo "---> ${QDATA_PATH}/keys/tma.key already exists, reusing..."
fi

echo "---> Constellation set up!"

#######################################################################
# Geth setup
#######################################################################
echo "*********** Setting up Geth ***********"


# Geth configuration
export GETH_PORT=${GETH_PORT:="30303"}
export GETH_RPC_PORT=${GETH_RPC_PORT:="8545"}
export GETH_RPC_ADDR=${GETH_RPC_ADDR:="0.0.0.0"}
export GETH_RPC_API=${GETH_RPC_API:="admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum"}

# Print Geth configuration
env | grep "GETH_"

# Raft configuration
export RAFT_PORT=${RAFT_PORT:="50400"}
export RAFT_BLOCKTIME=${RAFT_BLOCKTIME:="50"}
export RAFT_JOIN_EXISTING=${RAFT_JOIN_EXISTING:="0"}

# Print Geth configuration
env | grep "RAFT_"

# Make data dir if it doesnt exist
mkdir -p ${QDATA_PATH}/dd

# Create node key
if [ ! -z "${QDATA_PATH}/dd/nodekey" ]; then
    echo "---> \"${QDATA_PATH}/dd/nodekey\" does not exist. Generating new one..."
    bootnode -genkey "${QDATA_PATH}/dd/nodekey"
else
    echo "---> Node key already exists, reusing..."
fi
ENODE=$(bootnode -nodekey "${QDATA_PATH}/dd/nodekey" -writeaddress)
echo "ENODE=${ENODE}"

# Set up static-nodes.json
echo "[\"enode://${ENODE}@${INTERNAL_IP}:${GETH_PORT}?discport=0&raftport=${RAFT_PORT}\"]" > "${QDATA_PATH}/dd/static-nodes.json"

# Check if passwords.txt has to be created
if [ ! -f "${QDATA_PATH}/passwords.txt" ]; then
    echo "---> ${QDATA_PATH}/passwords.txt doesnt exist, creating one"

    # Create password if not exists and write to passwords.txt
    if [ -z "${GETH_ACCOUNT_PASSWORD}" ]; then
        echo "---> No GETH_ACCOUNT_PASSWORD provided. Generating one..."
        GETH_ACCOUNT_PASSWORD="$(openssl rand -hex 32)"
    fi
    echo "${GETH_ACCOUNT_PASSWORD}" > ${QDATA_PATH}/passwords.txt
    echo "GETH_ACCOUNT_PASSWORD=***"

    if [ -z ${GETH_ACCOUNT} ]; then
        echo "---> No GETH_ACCOUNT provided. Generating new account..."
        export GETH_ACCOUNT=$(geth --datadir=${QDATA_PATH}/dd --password ${QDATA_PATH}/passwords.txt account new | cut -c 11-50)
    fi
    echo "GETH_ACCOUNT=${GETH_ACCOUNT}"
else
    echo "---> ${QDATA_PATH}/passwords.txt already exists, reusing it..."
fi

# General
GETH_ARGS="--datadir ${QDATA_PATH}/dd"
GETH_ARGS="$GETH_ARGS --port ${GETH_PORT}"
GETH_ARGS="$GETH_ARGS  --emitcheckpoints"

# Raft
GETH_ARGS="$GETH_ARGS --raft"
GETH_ARGS="$GETH_ARGS --raftblocktime ${RAFT_BLOCKTIME}" # default: 50
GETH_ARGS="$GETH_ARGS --raftport ${RAFT_PORT}" # default: 54000
GETH_ARGS="$GETH_ARGS --raftjoinexisting ${RAFT_JOIN_EXISTING}" # default: 0

# Rpc
GETH_ARGS="$GETH_ARGS --rpc"
GETH_ARGS="$GETH_ARGS --rpcport ${GETH_RPC_PORT}" # default: 8545
GETH_ARGS="$GETH_ARGS --rpcaddr ${GETH_RPC_ADDR}"
GETH_ARGS="$GETH_ARGS --rpcapi ${GETH_RPC_API}"

# P2P
GETH_ARGS="$GETH_ARGS --nodiscover"

# Account management
GETH_ARGS="$GETH_ARGS --unlock 0 --password ${QDATA_PATH}/passwords.txt"

# Write chaindata folder
if [ ! -d ${QDATA_PATH}/dd/geth/chaindata ]; then
  echo "---> No chain data found! Creating Genesis block..."

# Check if genesis.json exists, otherwise create it
if [ ! -f "${QDATA_PATH}/genesis.json" ]; then
    echo "---> No existing ${QDATA_PATH}/genesis.json file, generating one..."
    envsubst < "${CONTEXT_PATH}/config/genesis.json.template" > "${QDATA_PATH}/genesis.json"
else
    echo "---> ${QDATA_PATH}/genesis.json already exists, reusing it..."
fi
  geth --datadir ${QDATA_PATH}/dd init ${QDATA_PATH}/genesis.json
fi

# Create log folder if it doesn't exist
mkdir -p ${QDATA_PATH}/logs

# Start services
echo "---> Starting constellation node..."
nohup constellation-node --verbosity=4 $TMCONF 2>> ${QDATA_PATH}/logs/constellation.log &

echo "Starting Geth in 2 seconds..."
sleep 2

echo "---> Starting Quorum Geth node..."
PRIVATE_CONFIG=$TMCONF geth $GETH_ARGS
```

And this is my Docker file:

**Dockerfile**
```
FROM ubuntu:16.04

# Variable definitions
ENV CONSTELLATION_VERSION 0.2.0
ENV CONSTELLATION_FLAVOR ubuntu1604
ENV CONSTELLATION_FILE_NAME constellation-${CONSTELLATION_VERSION}-${CONSTELLATION_FLAVOR}
ENV CONSTELLATION_URL https://github.com/jpmorganchase/constellation/releases/download/v${CONSTELLATION_VERSION}/${CONSTELLATION_FILE_NAME}.tar.xz
ENV QUORUM_VERSION 2.0.0
ENV GO_VERSION=1.9.2
ENV PATH $PATH:/usr/local/go/bin

# Install system packages required
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ethereum/ethereum && \
    apt-get update && \
    apt-get install -y \
        build-essential \
        libdb-dev \
        libleveldb-dev \
        libsodium-dev \
        zlib1g-dev \
        libtinfo-dev \
        xz-utils \
        wget \
        curl \
        git \
        unzip \
        gettext-base \
        solc

# Install Node.js
RUN curl -sL http://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs

#######################################
# Constellation
#######################################

# Install constellation
RUN wget -q ${CONSTELLATION_URL} && \
    tar xf ${CONSTELLATION_FILE_NAME}.tar.xz && \
    cp ${CONSTELLATION_FILE_NAME}/constellation-node /usr/local/bin && \
    chmod 0755 /usr/local/bin/constellation-node && \
    rm -rf ${CONSTELLATION_FILE_NAME} ${CONSTELLATION_FILE_NAME}.tar.xz

#######################################
# Quorum
#######################################

# Install Go
RUN wget -q https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -xzvf go${GO_VERSION}.linux-amd64.tar.gz && \
    mv go /usr/local/go && \
    rm go${GO_VERSION}.linux-amd64.tar.gz

# Install Quorum
RUN wget -q https://github.com/jpmorganchase/quorum/archive/v${QUORUM_VERSION}.zip && \
    unzip v${QUORUM_VERSION}.zip && \
    cd quorum-${QUORUM_VERSION} && \
    make all && \
    cp build/bin/geth /usr/local/bin && \
    cp build/bin/bootnode /usr/local/bin && \
    cd .. && \
    rm -rf quorum-${QUORUM_VERSION} v${QUORUM_VERSION}.zip

RUN mkdir -p /qdata

ADD . /root/context

WORKDIR /root

CMD [ "/root/context/scripts/start.sh" ]

```

The Geth logs here:
```
quorum_0_1  | raft2018/01/29 18:54:26 INFO: 1 is starting a new election at term 2
quorum_0_1  | raft2018/01/29 18:54:26 INFO: 1 became candidate at term 3
quorum_0_1  | raft2018/01/29 18:54:26 INFO: 1 received MsgVoteResp from 1 at term 3
quorum_0_1  | raft2018/01/29 18:54:26 INFO: 1 became leader at term 3
quorum_0_1  | raft2018/01/29 18:54:26 INFO: raft.node: 1 elected leader 1 at term 3
quorum_0_1  | INFO [01-29|18:54:26] QUORUM-CHECKPOINT                        name=BECAME-MINTER
quorum_0_1  | INFO [01-29|18:54:26] Not minting a new block since there are no pending transactions
quorum_0_1  | INFO [01-29|18:54:26] persisted the latest applied index       index=3
quorum_0_1  | INFO [01-29|18:54:39] sending private tx                       data=6060604052341561000f57600080fd5b60405160208061011083398101604052808051600055505060db806100356000396000f30060606040526004361060525763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416632a1afcd98114605757806360fe47b11460795780636d4ce63c14608e575b600080fd5b3415606157600080fd5b6067609e565b60405190815260200160405180910390f35b3415608357600080fd5b608c60043560a4565b005b3415609857600080fd5b606760a9565b60005481565b600055565b600054905600a165627a7a72305820c16a2a4f0c443fc08b6d9090c60b2e5d1ca43963960d8f74e206c14c16f507190029000000000000000000000000000000000000000000000000000000000000002a privatefrom= privatefor=[]
quorum_0_1  | INFO [01-29|18:54:44] sent private tx                          data=                                                                                                                                                                           privatefrom= privatefor=[]
```

**Comment by MitchK** [comment]
It looks like it works when I remove the ```privateFor``` field completely.

```
var contractInstance = Contract.new(42, {
		from: argv.account,
		data: '0x' + root.bytecode,
		gas: 300000
		// , privateFor: []
	},
...
```

**Comment by fixanoid** [comment]
Quorum will fail a private txn if the correspondent's transaction manager is down or the key is unknown. Please reopen if this is still an issue. Thanks.
