### ISSUE TITLE
Incompatibility with web3 1.0

### ISSUE THREAD

**Issue by mohdrashid** [Consensys-Incorporated/quorum#276]
I am trying to deploy a contract using web3[obviously with blank privateFor]. With web3 0.20.4 it worked when tested. However, when using web3 1.0 it is giving the blow error.

Error: Returned error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes
    at Object.ErrorResponse (xxx/node_modules/web3-core-helpers/src/errors.js:29:16)
    at xxx/node_modules/web3-core-requestmanager/src/index.js:137:36
    at XMLHttpRequest.request.onreadystatechange (xxx/node_modules/web3-providers-http/src/index.js:77:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/xx/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (xx/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/xx/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/xx/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by coeniebeyers** [comment]
I can confirm that web3 1.0 works with Quorum. From your error message:
```
Error: Returned error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes
```
there is a `0x` missing in one of the hex strings.

**Comment by mohdrashid** [comment]
I verified, I am running similar setup as in web3 0.20.4 with same set of commands. The funny part part is that it works well in testrpc. However, when i switch to quorum it gives me this error.

**Comment by coeniebeyers** [comment]
This is an issue inherited from geth 1.7.2: https://github.com/ConsenSys/ethjsonrpc/issues/43, https://github.com/ConsenSys/ethjsonrpc/issues/26

Just add 0x and it should work.

The QNM uses web3 1.0 with Quorum without issue: https://github.com/ConsenSys/QuorumNetworkManager/blob/master/package.json

**Comment by mohdrashid** [comment]
When I add 0x before the address,

it throws this error

```bash

Error: Provided address "0x0xed9d02e382b34818e88B88a309c7fe71E65f419d" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.

```

**Comment by mohdrashid** [comment]
Adding '0x' before the bytecode solved the issue. 

Thanks all
