### ISSUE TITLE
Running admin.peers does not display properly with SyntaxError.

### ISSUE THREAD

**Issue by hikaru-taka** [Consensys-Incorporated/quorum#313]
#### System information

OS: Ubuntu 16.04.2
Quorum Version: 1.2.0  7-node cluster

Geth
Version: 1.5.0-unstable
Git Commit: 647025ed8a504decfb11ac29bb44b3b2db703071
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux

block Number: 3174074

When you run admin.peers with Geth JavaScript console, the following error will be displayed.
It was displayed normally, when it was just started up but it returns as an error later on.

````
> admin.peers
Error: Invalid JSON RPC response: {"error":{"SyntaxError: json: cannot unmarshal number 43014389240597751355456802087224241404214818066677243895187144519701908807402766450080037048708831388351066913561678458369360425090555254117823783753967854153050908619646927159616730335012428471341895107566459938963131206062087564192558002425388889130230321081313141395379446007890001020682895954307626955398158786823948194897167255315989570074559493274476761795159638315961302891295220995740653449047649486526735610966109538404090752162400390131211739751285574187131334916255407094162682980285093786383655018637674976909062651163487779971519198050197995419574378627737644008626240927274706631137331198656658100151106698208470737475338339731008692480705814369136242534 into Go value of type float64":"SyntaxError: json: cannot unmarshal number 43014389240597751355456802087224241404214818066677243895187144519701908807402766450080037048708831388351066913561678458369360425090555254117823783753967854153050908619646927159616730335012428471341895107566459938963131206062087564192558002425388889130230321081313141395379446007890001020682895954307626955398158786823948194897167255315989570074559493274476761795159638315961302891295220995740653449047649486526735610966109538404090752162400390131211739751285574187131334916255407094162682980285093786383655018637674976909062651163487779971519198050197995419574378627737644008626240927274706631137331198656658100151106698208470737475338339731008692480705814369136242534 into Go value of type float64","code":-32603},"id":7,"version":"2.0"}
    at web3.js:3122:20
    at web3.js:6026:15
    at get (web3.js:5926:38)
    at <unknown>
````

Also, when I am not connecting with other nodes, it works well as follows.

````
> admin.peers
[]
````

Please let me know if anyone has solution for this.

**Comment by jpmsam** [comment]
@hikaru-taka Please upgrade to `v2.0.2` and it should work.
