### ISSUE TITLE
geth node unable to start

### ISSUE THREAD

**Issue by kjroger94** [Consensys-Incorporated/quorum#368]
#### System information

Geth version: `geth version`
1.7.2-stable-d4a1b095

OS & Version: Windows/Linux/OSX
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Branch, Commit Hash or Release: `git status`
I don't remember which branch I pulled it from because I used 2 branches, one had a reported issue with permissioned flag so I switched to another. I really can't remember. How can I check?

#### Expected behaviour
geth node should start

#### Actual behaviour
nohup: appending output to 'nohup.out'
WARN [05-06|07:14:42] No etherbase set and no accounts found as default
INFO [05-06|07:14:42] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-d4a1b095/linux-amd64/go1.9.4
INFO [05-06|07:14:42] Allocated cache and file handles         database=/home/ubuntu/newworkdir/qdata/dd3/geth/chaindata cache=128 handles=1024
WARN [05-06|07:14:42] Upgrading database to use lookup entries
INFO [05-06|07:14:42] Initialised chain configuration          config="{ChainID: 1 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 1 EIP155: <nil> EIP158: 1 Byzantium: 1 IsQuorum: true Engine: unknown}"
WARN [05-06|07:14:42] Ethash used in full fake mode
INFO [05-06|07:14:42] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [05-06|07:14:42] Loaded most recent local header          number=0 hash=fe3e45…e62c07 td=0
INFO [05-06|07:14:42] Loaded most recent local full block      number=0 hash=fe3e45…e62c07 td=0
INFO [05-06|07:14:42] Loaded most recent local fast block      number=0 hash=fe3e45…e62c07 td=0
INFO [05-06|07:14:42] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-06|07:14:42] Database deduplication successful        deduped=0
INFO [05-06|07:14:42] Starting P2P networking
INFO [05-06|07:14:42] starting raft protocol handler
INFO [05-06|07:14:42] RLPx listener up                         self="enode://9578a3fe7690c74eaae591ae1ff60adab3d9a0e5ac5a529ff5e4aa5f6e66e11cf8565f396b2fcc527da5d4c7698e7aa4d9169590eced38897cfb8f492d86e3e1@[::]:21002?discport=0"
INFO [05-06|07:14:42] loaded the latest applied index          lastAppliedIndex=0
INFO [05-06|07:14:42] replaying WAL
INFO [05-06|07:14:42] loading WAL                              term=0 index=0
INFO [05-06|07:14:42] startRaft                                raft ID=3
INFO [05-06|07:14:42] starting a new raft log                  initial cluster size of=3
panic: error: could not create URL from local address: &{3 [149 120 163 254 118 144 199 78 170 229 145 174 31 246 10 218 179 217 160 229 172 90 82 159 245 228 170 95 110 102 225 28 248 86 95 57 107 47 204 82 125 165 212 199 105 142 122 164 217 22 149 144 236 237 56 137 124 251 143 73 45 134 227 225] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 5003 50403}

goroutine 1 [running]:
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).setLocalAddress(0xc4200a38c0, 0xc42015eb60)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:497 +0x1e5
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft(0xc4200a38c0)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:467 +0x66b
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).Start(0xc4200a38c0, 0xc4200a06c0)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:137 +0xf5
github.com/ethereum/go-ethereum/raft.(*RaftService).Start(0xc42015ecb0, 0xc4200a06c0, 0x0, 0x0)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/backend.go:84 +0x39
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc42039e780, 0x0, 0x0)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:198 +0xb77
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc42039e780)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:62 +0x2f
main.startNode(0xc4200a22c0, 0xc42039e780)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:230 +0x77
main.geth(0xc4200a22c0, 0x11044b8, 0xb2d05e00)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:218 +0x43
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xeafbc0, 0x1105c88, 0xc4200a22c0, 0xc4200a22c0, 0xc4204abf40)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42006a4e0, 0xc420010120, 0x12, 0x12, 0x0, 0x0)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x635
main.main()
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:207 +0x55

#### Steps to reproduce the behaviour
Created my own keystore and constellation keys and placed it in the folders just like 7nodes example and used the same script to start 3 nodes. 
./raft-init.sh
/raft-start.sh

**Comment by kjroger94** [comment]
Disregard. I was messing up my permissioned-nodes.json file. It is working now
