### ISSUE TITLE
Panic when receiving constellation payload

### ISSUE THREAD

**Issue by kegsay** [Consensys-Incorporated/quorum#454]
There's no `err` check when doing [this request](https://github.com/jpmorganchase/quorum/blob/ee498061b5a74bf1f3290139a53840345fa038cb/private/constellation/node.go#L108) which results in a panic on [this line](https://github.com/jpmorganchase/quorum/blob/ee498061b5a74bf1f3290139a53840345fa038cb/private/constellation/node.go#L112).

**Comment by fixanoid** [comment]
@Kegsay thanks for the report. Can you attach log of the panic and speculate on the reason that it was caused? Thanks.

**Comment by kegsay** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x93b495]

goroutine 35068 [running]:
github.com/ethereum/go-ethereum/private/constellation.(*Client).ReceivePayload(0xc42000e6f0, 0xc42280a840, 0x40, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/node.go:112 +0x135
github.com/ethereum/go-ethereum/private/constellation.(*Constellation).Receive(0xc4201cd9e0, 0xc42280a840, 0x40, 0x40, 0xc421a3d500, 0x1, 0x0, 0x0, 0x0)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:38 +0x13e
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc4204c28c0, 0x116bc80, 0xc421a3d500, 0xc4219894c0, 0xc4204c28c0, 0xc421a81c08, 0xc421a3d500, 0xc421a3d500, 0xf72c20)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:235 +0xd28
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc4207af500, 0x116bc80, 0xc421a3d500, 0xc4219894c0, 0x167b051cec07c1bd, 0x4b51bda, 0xc421989cc0, 0x33dd53f5508847eb, 0xc167d7f8ba44f9a, 0xe47a0df5, ...)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:138 +0x5b
github.com/ethereum/go-ethereum/core.ApplyTransaction(0xc4200aa200, 0xc4201d2000, 0x0, 0xc4219894c0, 0xc4234ab860, 0xc4234ab950, 0xc42365b440, 0xc422148ea0, 0xc421989400, 0x0, ...)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:121 +0x4e4
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc4204aa880, 0xc422149440, 0xc4234ab860, 0xc4234ab950, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:78 +0x69a
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc4201d2000, 0xc420261c00, 0x180, 0x180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1026 +0x1d69
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc4201d2000, 0xc420261c00, 0x180, 0x180, 0x0, 0x0, 0x0)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:885 +0x67
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc4200a36c0, 0xc420261000, 0x180, 0x180, 0xde49a0, 0x1151d50)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1366 +0x163
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc4200a36c0, 0xc4204857c0, 0xc420485798)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1341 +0x74
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).(github.com/ethereum/go-ethereum/eth/downloader.processFullSyncContent)-fm(0x8, 0x105d820)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:489 +0x2a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc421508a70, 0xc421c3fc80, 0xc420bd9070)
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:507 +0x51
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:507 +0xc3
```

Caused by network problems between the geth node and constellation most likely.

**Comment by andreaMWork** [comment]
I am facing this challenge when I perform several (~50 TXs) private parallels request through jmeter, it seems like constellation open several IPC socket.
Constellation logs I get is :
`Network.Socket.accept: resource exhausted (Too many open files) `
After this point geth crash all over the network with the above error
I am currently deploying geth and constellation on separate AWS instances (m5XL)
We have been changing the number of open files withouth help.
limit.conf:

ubuntu           soft       nofile          1000000
ubuntu           hard       nofile          1000000
root             soft       nofile          1000000
root             hard       nofile          1000000
ubuntu           -       nproc           819200
root             -       nproc           819200
ubuntu           -       memlock         unlimited
root             -       memlock         unlimited


the output of sudo lsof | grep ipc :
`ghc_worke 20778 20789           ubuntu   25u     unix 0xffff8803ea376800      0t0    6615462 node3.ipc type=STREAM`

**Comment by fixanoid** [comment]
@andreaMWork please open an issue on the constellation repo

**Comment by fixanoid** [comment]
Fixed in master
