### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd56e34]

### ISSUE THREAD

**Issue by TSRL** [Consensys-Incorporated/quorum#457]
Quorum geth crashes when manually launching a node

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd56e34]
```

#### System information

```
Geth
Version: 1.7.2-stable
Git Commit: e8f0ee91620fbd14385d56658da249c22a9704a2
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.9.4
Operating System: linux
```

OS & Version: Red Hat Enterprise Linux Server 7.5 (Maipo)

Branch, Commit Hash or Release: on branch master

#### Expected behaviour
The node launches and connects to the second node on another server in my network

#### Actual behaviour
geth crashes with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd56e34]

goroutine 92 [running]:
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).buildSnapshot(0xc4200cd8                                   c0, 0x0)
        /opt/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/sn                                   apshot.go:56 +0x314
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).triggerSnapshot(0xc4200c                                   d8c0, 0x5)
        /opt/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/sn                                   apshot.go:83 +0x18f
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).eventLoop(0xc4200cd8c0)
        /opt/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/ha                                   ndler.go:791 +0x743
created by github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft
        /opt/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/ha                                   ndler.go:485 +0x789
```

#### Steps to reproduce the behaviour
Launch manually a node on Red Hat machine then add address of the second node from another machine and the first node's address to static-nodes.json and permissioned-nodes.json, try to launch the first node again

`geth --nodiscover --verbosity 3 --networkid 10 --raft --rpc --rpcaddr [myIP] --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --datadir=/opt/quorumnet --permissioned --raftport=50401 --rpcport=22000 --port=21000 --unlock [my account] --password [myPassword]`

#### Backtrace

````
INFO [07-31|10:36:42] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-e8f0ee91/linux-amd64/go1.9.4
INFO [07-31|10:36:42] Allocated cache and file handles         database=/opt/quorumnet/geth/chaindata cache=128 handles=1024
INFO [07-31|10:36:42] Initialised chain configuration          config="{ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 1 EIP155: 0 EIP158:1                       Byzantium: 1 IsQuorum: true Engine: unknown}"
WARN [07-31|10:36:42] Ethash used in full fake mode
INFO [07-31|10:36:42] Initialising Ethereum protocol           versions="[63 62]" network=10
INFO [07-31|10:36:42] Loaded most recent local header          number=0 hash=205603…5ea65e td=0
INFO [07-31|10:36:42] Loaded most recent local full block      number=0 hash=205603…5ea65e td=0
INFO [07-31|10:36:42] Loaded most recent local fast block      number=0 hash=205603…5ea65e td=0
INFO [07-31|10:36:42] Loaded local transaction journal         transactions=0 dropped=0
INFO [07-31|10:36:42] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-31|10:36:42] Starting P2P networking
INFO [07-31|10:36:42] starting raft protocol handler
INFO [07-31|10:36:42] loaded the latest applied index          lastAppliedIndex=4
INFO [07-31|10:36:42] loading snapshot
INFO [07-31|10:36:42] applying snapshot to raft storage
INFO [07-31|10:36:42] updating cluster membership per raft snapshot
INFO [07-31|10:36:42] updated cluster membership
INFO [07-31|10:36:42] blockchain is caught up; no need to synchronize
INFO [07-31|10:36:42] replaying WAL
INFO [07-31|10:36:42] loading WAL                              term=0 index=0
INFO [07-31|10:36:42] RLPx listener up                         self="enode://dc8      278f7c9a9e75b592c293eeecc430df7fd5a93895da944f7efcee2fb12ceac37fe811e29c3d11445f5de8fd2991c579f4dbc5e73b5d0f243148ebe0844e692@[::]:21000?discport=0"
INFO [07-31|10:36:42] startRaft                                raft ID=1
INFO [07-31|10:36:42] remounting an existing raft log; connecting to peers.
raft2018/07/31 10:36:42 INFO: 1 became follower at term 4
raft2018/07/31 10:36:42 INFO: newRaft 1 [peers: [1], term: 4, commit: 5, applied: 4, lastindex: 5, lastterm: 4]
INFO [07-31|10:36:42] HTTP endpoint opened: http://192.168.65.103:22000
Unlocking account 0xfed8ff38dc7e6eab16f0ac49d0ea5ef1d25cb88f | Attempt 1/3
Passphrase: INFO [07-31|10:36:42] IPC endpoint opened: /opt/quorumnet/geth.ipc
INFO [07-31|10:36:42] ignoring expected ConfChangeAddNode for initial peer raftid=2
INFO [07-31|10:36:42] start snapshot                           applied index=4 last snapshot index=1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd56e34]

goroutine 92 [running]:
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).buildSnapshot(0xc4200cd8                                   c0, 0x0)
        /opt/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/sn                                   apshot.go:56 +0x314
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).triggerSnapshot(0xc4200c                                   d8c0, 0x5)
        /opt/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/sn                                   apshot.go:83 +0x18f
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).eventLoop(0xc4200cd8c0)
        /opt/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/ha                                   ndler.go:791 +0x743
created by github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft
        /opt/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/ha                                   ndler.go:485 +0x789

````

**Comment by fixanoid** [comment]
@TSRL its likely a node misconfig: once your initial node set is up, you need to add your nodes through raft.addPeer. Please read this doc that explains the steps in detail: https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md
