### ISSUE TITLE
Need a way to abort the panic mode

### ISSUE THREAD

**Issue by karapish** [Consensys-Incorporated/quorum#458]
Please check the Backtrace section below. I don't understand how to continue the execution on a node which hits a panic mode due to some reason. Currently I run 'vagrant destroy' and 'vagrant up', which is very inconvenient. 

--------------------------------------------
#### System information
ubuntu-xenial VM running on MacOS host

Geth version: `geth version`
Version: 1.7.2-stable

OS & Version: Windows/Linux/OSX
OSX

Branch, Commit Hash or Release: `git status`
HEAD detached at v2.0.2
nothing to commit, working directory clean

#### Expected behaviour
There should be a way to reset a node

#### Actual behaviour
One of the nodes is hitting a panic mode --> node is not operational

#### Steps to reproduce the behaviour
Upon request 

#### Backtrace

````
ERROR[07-31|19:21:07]
########## BAD BLOCK #########
Chain config: {ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 1 EIP155: 0 EIP158: 1 Byzantium: 1 IsQuorum: true Engine: unknown}

Number: 120
Hash: 0x0ee76c3c1cee6338c5946203bf314d95d0738429fe6b11dc6795002fa4f837f4
        receipt{status=0 cgas=0 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}


Error: invalid receipt root hash (remote: b64408da6b8fe39ab764af88ece1e8cca1c35fd988db57806e99138c629365a0 local: 703c035562d8e37c66f2f9461219b45c710e59c8d0d234f6b062107de627758c)
##############################

panic: failed to extend chain: invalid receipt root hash (remote: b64408da6b8fe39ab764af88ece1e8cca1c35fd988db57806e99138c629365a0 local: 703c035562d8e37c66f2f9461219b45c710e59c8d0d234f6b062107de627758c)

goroutine 258 [running]:
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).applyNewChainHead(0xc4201d71e0, 0xc427ab8750)
        /home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:869 +0x898
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).eventLoop(0xc4201d71e0)
        /home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:723 +0x5e5
created by github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft
        /home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:482 +0x789````

**Comment by fixanoid** [comment]
@karapish please pull and build from master. This bug has been addressed, but we havent released a new version yet.

**Comment by joelburget** [comment]
Hi @karapish, if you build from master and are still able to repro, then I'll take a closer look. Please include the contract you're running and any other repro instructions.
