### ISSUE TITLE
Error deploying big contracts on nodes in cloud

### ISSUE THREAD

**Issue by amitakamat** [Consensys-Incorporated/quorum#525]
#### System information

```
Geth
Version: 1.7.2-stable
Git Commit: 99a83767ccf0384a3b58d9caffafabb5b49bd73c
Quorum Version: 2.1.0
Architecture: amd64
Network Id: 1337
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

Operating System: Windows10

I am trying to deploy a contract on nodes running in cloud. I am using truffle to deploy my contract. On my local 7nodes example setup, the contract deploys successfully. I get the following error when I try to deploy the same contract on cloud. I have put the value for gas as max block gas limit ( eth.getBlock("latest) ). 

```
Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)
```

#### Expected behaviour
Contract gets deployed successfully without errors.

#### Actual behaviour
Error in contract deployment.
```
truffle migrate --reset
Using network 'development'.

Running migration: 2_deploy_eventprediction.js
  Deploying Parent...
  ... 0xac653b2710db1993f8dfede55307ad0da8774a904a5294b782a6bdad7b9b6eeb
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (C:\Users\I869664\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\contract.js:147:1)
    at C:\Users\I869664\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\method.js:142:1
    at C:\Users\I869664\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:89:1
    at C:\Users\I869664\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-migrate\index.js:225:1
    at C:\Users\I869664\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1
    at C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\web3-provider-engine\index.js:152:9
    at C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\async\internal\once.js:12:16
    at replenish (C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\async\internal\eachOfLimit.js:61:25)
    at C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\async\internal\eachOfLimit.js:71:9
    at eachLimit (C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\async\eachLimit.js:43:36)
    at C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\async\internal\doLimit.js:9:16
    at end (C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\web3-provider-engine\index.js:127:5)
    at C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\web3-provider-engine\subproviders\provider.js:20:5
    at XMLHttpRequest.request.onreadystatechange (C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\web3-providers-http\src\index.js:77:13)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\xhr2\lib\xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\xhr2\lib\xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\xhr2\lib\xhr2.js:509:12)
    at IncomingMessage.<anonymous> (C:\Users\I869664\Documents\github\scp-bc-qaas-examples\PredictionApp-Quorum\node_modules\xhr2\lib\xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I have used the following settings for setting the node on cloud.

genesis.json:

`{"config":{"chainId":959407790,"eip150Block":2,"eip150Hash":"0x0000000000000000000000000000000000000000000000000000000000000000","eip155Block":3,"eip158Block":3,"byzantiumBlock":1,"istanbul":{"epoch":30000,"policy":0},"isQuorum":true},"nonce":"0x0","timestamp":"0x5b981480","extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f85ad59400032e60c9a1480c3df460d126988df5a621f151b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0","gasLimit":"0xe0000000","difficulty":"0x1","mixHash":"0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365","coinbase":"0x0000000000000000000000000000000000000000","alloc":{"00032e60c9a1480c3df460d126988df5a621f151":{"balance":"0xde0b6b3a7640000"}},"parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000"}`

Istanbul start:

`geth --datadir /qdata/dd --port 30303 --identity testnet-9af0bcd4-dc9b-474c-9a21-b9b3e6ae84bb --ethstats testnet-9af0bcd4-dc9b-474c-9a21-b9b3e6ae84bb:xxx@testnet-9af0bcd4-dc9b-474c-9a21-b9b3e6ae84bb-http.testnet.svc.cluster.local:3000 --mine --minerthreads 1 --istanbul.requesttimeout 10000 --istanbul.blockperiod 1 --emitcheckpoints --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --networkid 959407790 --permissioned --nodiscover --verbosity 5`

If I try to reduce the gas value in Truffle config, I get the error:
**Contract transaction couldn't be found after 50 blocks**

This seems like an issue with big contracts as the example simplestorage contract deploys successfully. The big contract however deploys successfully on the local 7nodes setup.

Could you please help me with this issue any let me know if I need to change anything in the settings?

**Comment by fixanoid** [comment]
Is it possible to share the contract code?

**Comment by amitakamat** [comment]
The issue was the gas limit. The gas limit did not reach the target gas limit due to which the contract deployment was failing as it did not have enough gas for deployment. Upgrading quorum version fixed the problem. Thanks!
