### ISSUE TITLE
Observer node crash

### ISSUE THREAD

**Issue by jaguarg** [Consensys-Incorporated/quorum#65]
#### System information

Geth version: `geth version`
```
Geth
Version: 1.5.0-unstable
Git Commit: 6d0bd810484f4c56f7c9aebc229e1bdc56832ced
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/local/go
```

OS & Version: Windows/Linux/OSX
` Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64)`

Branch, Commit Hash or Release: `git status`
`HEAD detached at v1.0.2`

#### Actual behaviour
I issued a private transaction between node A and B.  My node C (observer) crashed and is not starting.
C does not have an associated  constellation node. I assumed that observers would not require it. Could that be the issue ? 

#### Backtrace

````
E0221 11:18:33.968268 core/quorum/block_voting.go:280] Unable to vote: Node is not configured for voting
I0221 11:18:38.974174 eth/downloader/downloader.go:326] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5239cd]

goroutine 190 [running]:
panic(0xc69640, 0xc42000e0a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc420e6b1f0, 0xc420cae100, 0x154d6a0, 0xc420e28900, 0xc42137f160, 0xc420e6b1f0, 0xc420cae100, 0xc421428ae0)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:241 +0xe4d
github.com/ethereum/go-ethereum/core.ApplyMessage(0x154ff60, 0xc420cae100, 0x154d6a0, 0xc420e28900, 0xc42137f160, 0xc420e28900, 0xc421384480, 0x76b6acecad000000, 0x0, 0x0, ...)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_transition.go:144 +0x65
github.com/ethereum/go-ethereum/core.ApplyTransaction(0xc4200864e0, 0xc4203eb7a0, 0xc42137f160, 0xc4201474a0, 0xc420147c20, 0xc421384480, 0xc420e28900, 0xc42137f0a0, 0x0, 0x0, ...)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:96 +0x385
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc4201b6d80, 0xc420e24ab0, 0xc4201474a0, 0xc420147c20, 0x21b463e3b5000000, 0x0, 0x0, 0x6ef8c092e64583ff, 0xc0ad6c991be0485b, 0x21b463e3b52f6201, ...)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:70 +0x3f0
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc4203eb7a0, 0xc4212cc000, 0x6, 0x800, 0x0, 0x0, 0x0)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:934 +0xfe1
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).insertChain(0xc420060a90, 0xc4212cc000, 0x6, 0x800, 0x160bf20, 0xc420cdbde0, 0xc4212ded80)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:176 +0x51
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).(github.com/ethereum/go-ethereum/eth.insertChain)-fm(0xc4212cc000, 0x6, 0x800, 0x4, 0x160bf20, 0x0)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:152 +0x48
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processContent(0xc42013a540, 0xf37078, 0xc420e2b010)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1379 +0xe2b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc420e2b010, 0xc420e5b920, 0xc42013a540)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:462 +0x57
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:462 +0xce
````

**Comment by patrickmn** [comment]
Indeed, in order to verify whether the node is party to a private transaction it encounters on the blockchain, it should have an associated constellation node (via PRIVATE_CONFIG) configured.
