### ISSUE TITLE
Private transactions possible only from coinbase account(s) of node(s)

### ISSUE THREAD

**Issue by golashr** [Consensys-Incorporated/quorum#840]
Hi,
We have Geth+IBFT+Tessera nodes deployed on distributed machines. So we are extending the quorum code. 

We are dealing with the private transactions feature. Our deployment of private contract between two nodes 'from' and 'to' **works fine** when we are using coinbase account of any node among 4 peers/validators nodes of the blockchain. 

#### System information
Geth version: `geth version`
instance: Geth/XXXXX-XXXX/v1.8.18-stable-ccb4e9bd(quorum-**v2.3.0**)/linux-amd64/go1.11.13
OS & Version: Windows/Linux/OSX
**Ubuntu 18.04.3 LTS**
Branch - **master** 
Commit Hash or Release: `git status`
https://github.com/jpmorganchase/quorum/commit/99f7fd6733a93ee7619d1c740e0d4cd7643b6700
https://www.npmjs.com/package/quorum-js - v**0.3.2** with **SSL client**
**tessera** **Release 0.9** 
#### Expected behaviour
We should be able to deploy contract using any EOA account on 'from' node. Since Quorum uses 0 gasprice, balance of the EOA account should not matter but still, this EOA account has some positive balance in 'ether'.

#### Actual behaviour
Our issue is, we are not able to deploy contract using any other EOA account other than the coinbase accounts of peer nodes. So 'from' node, not only I can use coinbase account of 'from' node but also coinbase account of 'to' node or any other validator node too. 

#### Error at client side
````
gasPrice  0x746a528800
FromAccount 0xd81c256b771b2825850e39e2d7efb8ab4ca44772 has balance of **3** ether
Nonce : 0
Error: Returned error: invalid argument 0: json: cannot unmarshal non-string into Go value of type common.Hash
    at Object.ErrorResponse (/Users/XXXX/Ledgerium/CoreLedgerium/ledgeriumutility/node_modules/web3-eth/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/XXXX/Ledgerium/CoreLedgerium/ledgeriumutility/node_modules/web3-eth/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/XXXX/Ledgerium/CoreLedgerium/ledgeriumutility/node_modules/web3/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/XXXX/Ledgerium/CoreLedgerium/ledgeriumutility/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/XXXX/Ledgerium/CoreLedgerium/ledgeriumutility/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/XXXX/Ledgerium/CoreLedgerium/ledgeriumutility/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/XXXX/Ledgerium/CoreLedgerium/ledgeriumutility/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

````

**Comment by prd-fox** [comment]
Can you reproduce this with our release of Quorum, instead of your modified version? If so, can you attach a script or the steps to reproduce?

It looks like the value sent to the RPC server is in an incorrect format - can you verify/ouput the data that you are sending from quorum.js?

**Comment by golashr** [comment]
@prd-fox 
 ```
[10-10|11:19:27.906|internal/ethapi/api.go:1511]                   sending private tx                       data=f4142540fe3bd9b6b0df83154b63e05dc5b716c681807473729a2fc3eb96ad9b69426185ac07c700a3ccada7ada12c31d389ff830e70969fc910d34a04e5b549                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              privatefor="[6od0tK0so8tuiIyvjxSEZgbEW9X0gQ3SK9P36U0QnXI=]"
TRACE[10-10|11:19:27.911|p2p/discover/table.go:311]                     Findnode failed                          id=da640e1a69e2af40 failcount=2  err="RPC timeout"
TRACE[10-10|11:19:27.911|p2p/server.go:708]                             Dial task done                           task="discovery lookup (16 results)"
TRACE[10-10|11:19:27.911|p2p/server.go:641]                             New dial task                            task="dyndial da332d1544f28b62 185.253.190.33:30303"
INFO [10-10|11:19:28.192|internal/ethapi/api.go:1513]                   sent private tx                          result=f4142540fe3bd9b6b0df83154b63e05dc5b716c681807473729a2fc3eb96ad9b69426185ac07c700a3ccada7ada12c31d389ff830e70969fc910d34a04e5b549 privatefor="[6od0tK0so8tuiIyvjxSEZgbEW9X0gQ3SK9P36U0QnXI=]"
TRACE[10-10|11:19:28.192|core/types/transaction_signing.go:239]         Vb before value offset                   Vb=37
TRACE[10-10|11:19:28.192|core/types/transaction_signing.go:241]         V before validating signature values     V=0
TRACE[10-10|11:19:28.192|core/types/transaction_signing.go:239]         Vb before value offset                   Vb=37
TRACE[10-10|11:19:28.192|core/types/transaction_signing.go:241]         V before validating signature values     V=0
TRACE[10-10|11:19:28.193|core/tx_pool.go:668]                           Discarding invalid transaction           hash=13d633…8fc29d err="insufficient funds for gas * price + value"
```
This log might help to our cause. So internally, it fails for insufficient funds. However, it has sufficient fund of 3 ether. Even I transfer 1000 ether to it, result is the same.

**Comment by prd-fox** [comment]
If the gas price is 0, then I don't see how the check that returns that error could ever happen. It also doesn't seem related to the error you were getting in your JS app, which states that the value sent to the RPC server could not be decoded.
Do you have a script or series of steps for me to reproduce this my end?

**Comment by golashr** [comment]
Yes. Our gas price is not zero. Strangely, it happens even when there is some balance in the account. Strangely enough, error at the JS app does not equate to the log. However, this is pretty consistent at my side. We have one project https://github.com/ledgerium-io/ledgeriumutility and one can try "Deploy Greeter smart contract" option on it. 
Example
```
node index.js protocol=http hostname=flinders01.ledgerium.io port=8545 readkeyconfig=true fromPubKey=YD2CbY+bQGLg776z45O9d4I37UTgNNOtW/PZxVS6PA8= toPubKey=6od0tK0so8tuiIyvjxSEZgbEW9X0gQ3SK9P36U0QnXI= testprivateTransactions=flinders01.ledgerium.io,flinders02.ledgerium.io,flinders03.ledgerium.io,flinders04.ledgerium.io,10100,8545,8545,8545
```
 Alternatively, we can have call and I can show it in a live session, if possible. Coinbase account with private keys to be add in ./keystore/privatekey.json file as first entry.

**Comment by prd-fox** [comment]
When I ran it, I found that the submitted transaction did not have a gas price of 0, which is what was set in the `txnParams`.

 Changing it to **non-hex** fixed it, i.e. `gasPrice: web3.utils.toHex(gasPrice)` to `gasPrice: gasPrice`. Could you try making the same change?

Otherwise, it ran fine for me.

**Comment by golashr** [comment]
No. Did not help. 
```
INFO [10-10|23:36:49.029|internal/ethapi/api.go:1511]                   sending private tx                       data=ad589dd33caf50ab3f7c12b317aa8c6602f78dc81d510e326f1d362c18b982dd14ff61caf8e2dd5baf2f48d12dc155c21cfbdba8d16b549933b2afcc21121885 privatefor="[6od0tK0so8tuiIyvjxSEZgbEW9X0gQ3SK9P36U0QnXI=]"
INFO [10-10|23:36:49.132|internal/ethapi/api.go:1513]                   sent private tx                          result=ad589dd33caf50ab3f7c12b317aa8c6602f78dc81d510e326f1d362c18b982dd14ff61caf8e2dd5baf2f48d12dc155c21cfbdba8d16b549933b2afcc21121885 privatefor="[6od0tK0so8tuiIyvjxSEZgbEW9X0gQ3SK9P36U0QnXI=]"
TRACE[10-10|23:36:49.132|core/types/transaction_signing.go:239]         Vb before value offset                   Vb=37
TRACE[10-10|23:36:49.132|core/types/transaction_signing.go:241]         V before validating signature values     V=0
TRACE[10-10|23:36:49.133|core/types/transaction_signing.go:239]         Vb before value offset                   Vb=37
TRACE[10-10|23:36:49.133|core/types/transaction_signing.go:241]         V before validating signature values     V=0
TRACE[10-10|23:36:49.133|core/tx_pool.go:668]                           Discarding invalid transaction           hash=a47361…bf66b5 err="insufficient funds for gas * price + value"
```

Please note that it works with coinbase account here..
```
from: {
   privateKey: '0x' + privateKeyFromAccount;
},
```

**Comment by prd-fox** [comment]
This seems to be purely an issue with the modifications made in your fork of Quorum. I'm sorry, but we don't have the time to debug changes not related to a release of, or the `master` branch version of, Quorum.

You may try editing the logging to output the details of the transaction and see what differences exist between the transactions when sent from the various accounts.

If you are able to reproduce this issue using Quorum itself, then please feel free to reopen or create a new ticket.

**Comment by golashr** [comment]
@prd-fox I understand. I checked it with the quorum latest image quorumengineering/quorum:latest and yes, this problem could not be reproduced. So it is applicable in our fork for sure.  I suspect the root cause could be something, it just can't be gasprice. Our EOA has balance and as I mentioned, the feature works with any of the coinbase accounts. I wonder if **you can suggest me the suspected area**. Thanks in advance.

**Comment by prd-fox** [comment]
I'm not sure what other areas to look at, but I would start by adding the following output to the logs:

- `from`
- `pool.currentState.GetBalance(from)`
- `tx.Cost()`

and check that the values are what you expect them to be. 

For what it's worth, I checked out your fork, and the log message line numbers don't line up with what it on the `main` branch, however this error can only be thrown from a single place, so I'm fairly certain that one of those values above isn't going to be what you expect.
