### ISSUE TITLE
'raft applied is out of range' causing panic

### ISSUE THREAD

**Issue by robinbryce** [Consensys-Incorporated/quorum#845]
I believe this is a recurence of #281

#### System information

Geth version: `geth version`
Geth
Version: 1.8.18-stable
Git Commit: c894c2d70eacf30740d03b53ed2fb39e42641295
Quorum Version: 2.2.5
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.11.12
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`
Quorum Version: 2.2.5

#### Expected behaviour

After restart the node catches up with the chain

#### Actual behaviour

Node 1 partialy catches up, restarts and panics. there after it panics every restart
Node 2 partialy catches up, restarts and panics. there after it panics every restart
Node 1 & Node 2 reach the same block, but are about 200 blocks behind the minter at that time

#### Steps to reproduce the behaviour

* 5 node network
* Continually create tx's on the nodes (load testing at moderate rate)
* Take two nodes down for a few hours .

#### Backtrace

````
TRACE[10-13|08:57:13.777|eth/sync.go:89]                         Sending batch of transactions            id=c61a11c33dfeeba2 conn=staticdial count=10 bytes=25.43kB
INFO [10-13|08:57:14.177|raft/handler.go:468]                    startRaft                                raft ID=4
INFO [10-13|08:57:14.254|raft/handler.go:471]                    remounting an existing raft log; connecting to peers.
raft2019/10/13 08:57:14 applied(11688) is out of range [prevApplied(13718), committed(13718)]
panic: applied(11688) is out of range [prevApplied(13718), committed(13718)]

goroutine 1 [running]:
log.(*Logger).Panicf(0xc00013d9f0, 0x113ea16, 0x3c, 0xc003307260, 0x3, 0x3)
        /usr/local/go/src/log/log.go:219 +0xdb
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x1f297f0, 0x113ea16, 0x3c, 0xc003307260, 0x3, 0x3)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raftLog).appliedTo(0xc0003fe310, 0x2da8)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/log.go:202 +0x15b
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.newRaft(0xc003a73728, 0xc0001182a0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:306 +0xa97
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.RestartNode(0xc003a73728, 0x35, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/node.go:224 +0x40
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft(0xc018d1a840)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:472 +0x7f4
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).Start(0xc018d1a840, 0xc000427180)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:142 +0xd7
github.com/ethereum/go-ethereum/raft.(*RaftService).Start(0xc018f68f00, 0xc000427180, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/backend.go:91 +0x39
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc000426f00, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:206 +0xa92
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc000426f00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc00016c160, 0xc000426f00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:292 +0xb5
main.geth(0xc00016c160, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:275 +0xe1
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xf55700, 0x11af838, 0xc00016c160, 0xc00016c160, 0xc0004f9f58)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0001221a0, 0xc0000e4000, 0x23, 0x24, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x59d
main.main()
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:261 +0x55
````

#### Logs etc

We have a lot of log data from all nodes for this incident. If there is interest, I can work it into a useful shape.

**Comment by fixanoid** [comment]
@robinbryce would it be possible for you to upgrade to v2.3.0 and see if this is still happening? Thanks

**Comment by robinbryce** [comment]
Yes, thats in progress thanks

**Comment by kjroger94** [comment]
I checked it with v2.3.0 and it is still happening. If I stop all the nodes and restart them, 4/5 nodes that I have running are getting this error

```
INFO [10-16|10:53:30.138] remounting an existing raft log; connecting to peers.
raft2019/10/16 10:53:30 1 state.commit 416255 is out of range [416348, 418520]
panic: 1 state.commit 416255 is out of range [416348, 418520]

goroutine 1 [running]:
log.(*Logger).Panicf(0xc42027ec30, 0x11de10f, 0x2b, 0xc4201b3040, 0x4, 0x4)
        /usr/local/go/src/log/log.go:219 +0xdb
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x1f140f0, 0x11de10f, 0x2b, 0xc4201b3040, 0x4, 0x4)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raft).loadState(0xc42767c000, 0x48da, 0x1, 0x659ff, 0x0, 0x0, 0x0)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:1191 +0x1c7
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.newRaft(0xc4266216e0, 0xc4202e8320)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:303 +0xc39
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.RestartNode(0xc4266216e0, 0x35, 0x0)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/node.go:224 +0x40
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft(0xc4205caf20)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:472 +0x90c
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).Start(0xc4205caf20, 0xc4200a0500)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:142 +0xfb
github.com/ethereum/go-ethereum/raft.(*RaftService).Start(0xc420282600, 0xc4200a0500, 0xc4204b19f8, 0x0)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/raft/backend.go:91 +0x39
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc4200a0000, 0x0, 0x0)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:206 +0xba3
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc4200a0000)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc4205ca000, 0xc4200a0000)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:292 +0xb5
main.geth(0xc4205ca000, 0x0, 0x0)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:275 +0xed
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xff4b40, 0x1258f78, 0xc4205ca000, 0xc4205ca000, 0xc4204b1f40)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4205b2000, 0xc420010240, 0x22, 0x24, 0x0, 0x0)
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x635
main.main()
        /home/ubuntu/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:261 +0x55

```

**Comment by robinbryce** [comment]
Thanks for doing that!

**Comment by kjroger94** [comment]
Can someone explain what exactly is failing here - 

```
remounting an existing raft log; connecting to peers.
raft2019/10/16 10:53:30 1 state.commit 416255 is out of range [416348, 418520]
panic: 1 state.commit 416255 is out of range [416348, 418520]
```
what is it trying to do when it says - remounting existing raft log and then trying to commit a _state_ and then it says it has _a state_ but it is _out of the range_.  I just want to understand what exactly is failing, where and why does this happen

**Comment by zzy96** [comment]
Hi @kjroger94 

This failure essentially means Raft WAL is corrupted. The hard state read from it is not within committed and lastIndex. I am able to reproduce this issue when the network is under high load. I feel the fundamental cause for this issue and #850 #852 is the same but need more investigation to validate.

**Comment by kjroger94** [comment]
Is there a way to recover that node? The node just fails to start. Or, the only way would be to get rid of this node and get another in place of this?

**Comment by robinbryce** [comment]
Yes, our plan for this scenario is simply to discard the node and start again. Essentially by deleting its disc yet retaining its old raft id so it can do a removePeer / addPeer when it comes back up with a clean disc

**Comment by zzy96** [comment]
Hi @robinbryce @kjroger94 

After some analysis, I am getting closer to the root cause of this particular issue. In raft mode, `hard state` & `entries` are written into WAL before raft entries are processed, but `applied index` is written into the node's local level db only after completion of processing each raft entry. If a node is stopped/ restarted during a large list of entries under processing (particularly when calling `applyRaftSnapshot` which takes time to sync blocks from peers). `hard state` & `entries` are moved forward but `applied index` is not updated. I will raise a fix for this shortly. Thanks for the patience!

**Comment by robinbryce** [comment]
That sounds like a very strong candidate. Thanks very much!
