### ISSUE TITLE
Error EOF while sending private transaction

### ISSUE THREAD

**Issue by diestrin** [Consensys-Incorporated/quorum#849]
#### System information

Geth version: `geth version`
```
Version: 1.8.18-stable
Git Commit: c894c2d70eacf30740d03b53ed2fb39e42641295
Quorum Version: 2.2.5
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.11.12
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

OS & Version: `Linux node-0 4.14.127+ #1 SMP Tue Jun 18 23:08:40 PDT 2019 x86_64 Linux`

#### Expected behaviour
To install a private contract sending a private transaction

#### Actual behaviour
```
loadScript('/7nodes/private-contract.js')
err creating contract Error: EOF
    at web3.js:3143:20
    at web3.js:6372:29
    at github.com/ethereum/go-ethereum/console.(*bridge).Send-fm (console.go:116)
    at web3.js:6366:5
    at web3.js:5077:20
    at web3.js:3007:13
    at /7nodes/private-contract.js:11:14
    at github.com/ethereum/go-ethereum/internal/jsre.(*JSRE).loadScript-fm (jsre.go:79)
    at <anonymous>:1:1
```

#### Steps to reproduce the behaviour
I created a network using either istanbul and raft, happens on both, using tessera manager

#### Backtrace
```
INFO [10-14|19:35:21.940] sending private tx                       data=6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029000000000000000000000000000000000000000000000000000000000000002a privatefrom= privatefor="[HYouch49KSf5NRDAJ8Jjo/gaM9JVOa1PnmR3/1C8cUE=]"
ERROR[10-14|19:35:21.944] goroutine 1154 [running]:
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func1(0xc018f35110, 0x1324180, 0xc0002f4050)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:132 +0xf2
panic(0xf48ca0, 0x1ad2dc0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).SendTransaction(0xc0002040a0, 0x131dfe0, 0xc018f522d0, 0x7d5c4d5909e5fa06, 0xc9613c5b3e082ff4, 0x5ceabda2, 0x0, 0xc0001b0350, 0x0, 0x0, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:1400 +0x86a
reflect.Value.call(0xc000483980, 0xc018f3c440, 0x13, 0x109c81e, 0x4, 0xc018f44120, 0x3, 0x4, 0xc018f522d0, 0xc018f44120, ...)
	/usr/local/go/src/reflect/value.go:447 +0x454
reflect.Value.Call(0xc000483980, 0xc018f3c440, 0x13, 0xc018f44120, 0x3, 0x4, 0x1, 0x1, 0x0)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc018f35110, 0x131df20, 0xc018f320c0, 0x1324180, 0xc0002f4050, 0xc018f440c0, 0xc0002f4340, 0x0, 0xf3a3c0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:313 +0x953
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc018f35110, 0x131df20, 0xc018f320c0, 0x1324180, 0xc0002f4050, 0xc018f440c0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:334 +0x1a6
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc018f35110, 0x131dfe0, 0xc018f521e0, 0x1324180, 0xc0002f4050, 0x10a5c01, 0x1, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:192 +0x36e
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc018f35110, 0x131dfe0, 0xc018f521e0, 0x1324180, 0xc0002f4050, 0x1)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:223 +0x65
github.com/ethereum/go-ethereum/rpc.(*Server).ServeHTTP(0xc018f35110, 0x131c660, 0xc0001d60e0, 0xc0000d4f00)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:253 +0x4a6
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x131c660, 0xc0001d60e0, 0xc0000d4f00)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rs/cors/cors.go:190 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc0004650a0, 0x131c660, 0xc0001d60e0, 0xc0000d4f00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/ethereum/go-ethereum/rpc.(*virtualHostHandler).ServeHTTP(0xc0004650c0, 0x131c660, 0xc0001d60e0, 0xc0000d4f00)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:317 +0x1c7
net/http.serverHandler.ServeHTTP(0xc018f4d450, 0x131c660, 0xc0001d60e0, 0xc0000d4f00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc018f3e000, 0x131df20, 0xc02955dc80)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

My genesis file
```
{"alloc":{"0x7c82b61411441d90e98df621e6c78f0d902eaddd":{"balance":"1000000000000000000000000000"}},"coinbase":"0x0000000000000000000000000000000000000000","config":{"chainId":21486396,"homesteadBlock":1,"eip150Block":2,"eip150Hash":"0x0000000000000000000000000000000000000000000000000000000000000000","eip155Block":3,"eip158Block":3,"isQuorum":true},"extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f85ad5947c82b61411441d90e98df621e6c78f0d902eadddb8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0","gasLimit":"0x47b760","difficulty":"0x1","mixHash":"0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365","nonce":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","timestamp":"0x00","number":"0x0","gasUsed":"0x0"}
```

My node start command:
```
geth \
  --identity node-diegokqx-testfca-quorum-casaptb-testfca \
  --datadir /data/node \
  --permissioned \
  --nodiscover \
  --verbosity 5 \
  --networkid 21486396 \
  --rpc \
  --rpccorsdomain "*" \
  --rpcvhosts "*" \
  --rpcaddr 0.0.0.0 \
  --rpcport 30515 \
  --unlock $ADDRESS \
  --password /var/eth/secrets/account-password.txt \
  --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
  --port 31730 \
  --emitcheckpoints --raft --raftport 31586
```

My tessera start command
```
tessera -configfile /var/eth/config/tessera-config.json
```

My tessera-config.json
```
{
  "useWhiteList": false,
  "jdbc": {
    "username": "sa",
    "password": "",
    "url": "jdbc:h2:/data/node/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
    "autoCreateTables": true
  },
  "serverConfigs": [
    {
      "app": "ThirdParty",
      "enabled": true,
      "serverAddress": "http://node.diegokqx-testfca-quorum-casaptb.svc.cluster.local:30502",
      "communicationType": "REST"
    },
    {
      "app": "Q2T",
      "enabled": true,
      "serverAddress": "unix:/data/node/tm.ipc",
      "communicationType": "REST"
    },
    {
      "app": "P2P",
      "enabled": true,
      "serverAddress": "http://node.diegokqx-testfca-quorum-casaptb.svc.cluster.local:30429",
      "sslConfig": {
        "tls": "OFF"
      },
      "communicationType": "REST"
    },
    {
      "app": "ADMIN",
      "enabled": true,
      "serverAddress": "http://127.0.0.1:9090",
      "sslConfig": {
        "tls": "OFF"
      },
      "communicationType": "REST"
    }
  ],
  "peer": [],
  "keys": {
    "passwordFile": "/var/eth/secrets/manager-password.txt",
    "keyData": [
      {
        "privateKeyPath": "/data/node/node.key",
        "publicKeyPath": "/data/node/node.pub"
      }
    ]
  },
  "disablePeerDiscovery": false,
  "alwaysSendTo": []
}
```

**Comment by fixanoid** [comment]
@diestrin `geth` startup requires passing PRIVATE_CONFIG paramtere like so: `PRIVATE_CONFIG=/data/node/tm.ipc geth ...` for the Quorum node to be linked to corresponding Tessera instance. The value is set to be the unix socket from the Tessera Q2T config. Are you doing that?

**Comment by diestrin** [comment]
@fixanoid thanks I was indeed missing this, but after adding it I'm still getting some errors sending private tx.
```
loadScript('/7nodes/private-contract.js')

err creating contract Error: Non-200 status code: &{Status:404 Not Found StatusCode:404 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Tue, 15 Oct 2019 02:08:00 GMT] Content-Type:[text/plain] Content-Length:[73] Server:[Jetty(9.4.z-SNAPSHOT)]] Body:0xc028ce8000 ContentLength:73 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc028ce6000 TLS:<nil>}
    at web3.js:3143:20
    at web3.js:6372:29
    at github.com/ethereum/go-ethereum/console.(*bridge).Send-fm (console.go:116)
    at web3.js:6366:5
    at web3.js:5077:20
    at web3.js:3007:13
    at /7nodes/private-contract.js:11:14
    at github.com/ethereum/go-ethereum/internal/jsre.(*JSRE).loadScript-fm (jsre.go:79)
    at <anonymous>:1:1
```
In the peer logs I can see:
```
DEBUG[10-15|02:08:00.022] New round                                address=0x51E252E7E1db8ebBb6eBa6941E32cBe3d3f44011 old_round=0  old_seq=114 old_proposer=0x51E252E7E1db8ebBb6eBa6941E32cBe3d3f44011 new_round=0 new_seq=115 new_proposer=0x51E252E7E1db8ebBb6eBa6941E32cBe3d3f44011                                                                                                                                       valSet="[0x51E252E7E1db8ebBb6eBa6941E32cBe3d3f44011 0xD210d0e7A7A50B3779AafC6Cdc5624DdD29668fb]" size=2     IsProposer=true
INFO [10-15|02:08:00.566] sending private tx                       data=6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029000000000000000000000000000000000000000000000000000000000000002a privatefrom= privatefor="[PNBtg4OapPED/FGZeaBbgBDw/D9BQcR8ANTktwfcKTI=]"
INFO [10-15|02:08:00.652] sent private tx                          data=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   privatefrom= privatefor="[PNBtg4OapPED/FGZeaBbgBDw/D9BQcR8ANTktwfcKTI=]"
TRACE[10-15|02:08:01.000] handleRequest                            address=0x51E252E7E1db8ebBb6eBa6941E32cBe3d3f44011 state="Accept request" seq=115 number=115 hash=301016…b411f9
INFO [10-15|02:08:01.010] Committed                                address=0x51E252E7E1db8ebBb6eBa6941E32cBe3d3f44011 hash=301016…b411f9 number=115
DEBUG[10-15|02:08:01.018] Trie cache stats after commit            misses=0 unloads=0
DEBUG[10-15|02:08:01.019] Trie cache stats after commit            misses=0 unloads=0
INFO [10-15|02:08:01.019] Successfully sealed new block            number=115 sealhash=99c46f…53cd1b hash=301016…b411f9 elapsed=999.799ms
INFO [10-15|02:08:01.019] 🔨 mined potential block                  number=115 hash=301016…b411f9
DEBUG[10-15|02:08:01.019] Reinjecting stale transactions           count=0
TRACE[10-15|02:08:01.020] Propagated block                         hash=301016…b411f9 recipients=1 duration=2562047h47m16.854s
TRACE[10-15|02:08:01.020] Announced block                          hash=301016…b411f9 recipients=0 duration=2562047h47m16.854s
TRACE[10-15|02:08:01.020] Propagated block                         id=ab4ff0eb94c7d464 conn=inbound number=115 hash=301016…b411f9 td=116
INFO [10-15|02:08:01.023] Commit new mining work                   number=116 sealhash=be330d…5b3660 uncles=0 txs=0 gas=0 fees=0 elapsed=2.433ms
TRACE[10-15|02:08:01.023] Received a final committed proposal      address=0x51E252E7E1db8ebBb6eBa6941E32cBe3d3f44011 state=Committed
TRACE[10-15|02:08:01.023] Catch up latest proposal                 address=0x51E252E7E1db8ebBb6eBa6941E32cBe3d3f44011 old_round=0  old_seq=115 number=115 hash=301016…b411f9
```

**Comment by diestrin** [comment]
Update: this only happens when attaching to geth from the outside. If I ssh into the container and do `geth attach /data/node/geth.ipc` and execute the same contract, it does work. Is it possible to send private transactions from outside the node?

**Comment by prd-fox** [comment]
Is there anything in the Tessera node's log when the transaction fails?

**Comment by fixanoid** [comment]
@diestrin you can send public and private txns outside the node, but the sample you are using (private-contract.js) is only intended to be run as geth console.

Actual examples of using web3js and other libraries can be found here: https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes/samples
