### ISSUE TITLE
Geth crashes if no transaction manager is defined and private transaction received

### ISSUE THREAD

**Issue by SatpalSandhu61** [Consensys-Incorporated/quorum#863]
#### System information
Version: 1.8.18-stable
Git Commit: a15ccedbc095a3628bdffe0364f4e53b8a93ebf9
Quorum Version: 2.3.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.4
Operating System: darwin
GOPATH=/Users/satpal/Documents/go-workspace/
GOROOT=/usr/local/go

#### Expected behaviour

If a private transaction is received and no transaction manager is defined then the private transaction should be rejected with a warning message.
Also, geth process should not crash.

#### Actual behaviour

Geth process crashes with stack trace shown further below.
This causes the API call to return with "err creating contract Error: EOF".

#### Steps to reproduce the behaviour

- Start up geth node without the `PRIVATE_CONFIG` environment variable defined.
- geth attach qdata/dd1/geth.ipc
- loadScript("private-contract.js")

#### Backtrace

````
INFO [10-21|14:46:31.118] sending private tx                       data=<contract data>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x46a7055]
 
goroutine 1062 [running]:
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI)
.SendTransaction(0xc420120700, 0x4ee6980, 0xc421d66cf0, 0x1848b382e3029ded,
0x71fec709a3888be8, 0x9d415fe6, 0x0, 0xc421acfa50, 0x0, 0x0, ...)
        /Users/satpal/Documents/go-workspace/src/github.com/ethereum/go-eth
ereum/internal/ethapi/api.go:1401 +0x875
reflect.Value.call(0xc420311600, 0xc4202c78d0, 0x13, 0x4d24ab6, 0x4, 0xc421
aca9c0, 0x3, 0x4, 0xc421d66cf0, 0xc421aca9c0, ...)
        /usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc420311600, 0xc4202c78d0, 0x13, 0xc421aca9c0, 0x3, 0x4
, 0x1, 0x1, 0xc42004aa70)
        /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc42001a9c0, 0x4ee6980, 0xc421ab98f0, 0x4eecda0, 0xc421aacc80, 0xc421aca960, 0xc420f34738, 0x402c029, 0x8)
        /Users/satpal/Documents/go-workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:313 +0x8fa
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc42001a9c0, 0x4ee6980, 0xc421ab98f0, 0x4eecda0, 0xc421aacc80, 0xc421aca960)
        /Users/satpal/Documents/go-workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:334 +0x1a6
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0xc421ace5a0, 0xc42001a9c0, 0xc42036dbb0, 0x4eecda0, 0xc421aacc80, 0xc4202d06b8, 0x1, 0x1, 0xc42021fe00)
        /Users/satpal/Documents/go-workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:204 +0xad
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
        /Users/satpal/Documents/go-workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:199 +0x28c
````

**Comment by zzy96** [comment]
I think this PR may solve the issue. https://github.com/jpmorganchase/quorum/pull/836

**Comment by SatpalSandhu61** [comment]
Closing this ticket as the issue is actually resolved under ticket # 834.
