### ISSUE TITLE
Contract calling another contract gives 'evm: execution reverted'

### ISSUE THREAD

**Issue by aditya-skeps** [Consensys-Incorporated/quorum#869]
I am running 7nodes example. This is just a simple example of a contract calling another contract. Have provided my javascript code as well.

#### System information

Geth version: 1.8.18-stable

OS & Version: OSX

Web3: 1.0.0-beta.35

#### Expected behaviour
Calling C2 getters and setters should get and set value on contract C1.

#### Actual behaviour
Does not work, getting evm: execution reverted. No values are returned and web3 throws an error. I have tried these contracts on Remix and it works as expected.

#### Steps to reproduce the behaviour
Download the latest 7nodes, run the below index.js file having contracts C1 and C2 in the same folder.

#### Backtrace

````
TRACE[11-04|10:56:31.601] Pooled new future transaction            hash=46e319…575833 from=0xed9d02e382b34818e88B88a309c7fe71E65f419d to=0x4D3bfd7821E237fFE84209d8E638f9f309865b87
TRACE[11-04|10:56:31.601] Promoting queued transaction             hash=46e319…575833
TRACE[11-04|10:56:31.601] Promoting queued transaction             hash=46e319…575833
INFO [11-04|10:56:31.601] Submitted transaction                    fullhash=0x46e31931d3cc3076a897e9b92685e91646d9c20a37e551c60281db2faa575833 recipient=0x4D3bfd7821E237fFE84209d8E638f9f309865b87
INFO [11-04|10:56:31.601] QUORUM-CHECKPOINT                        name=TX-CREATED                                                        tx=0x46e31931d3cc3076a897e9b92685e91646d9c20a37e551c60281db2faa575833 to=0x4D3bfd7821E237fFE84209d8E638f9f309865b87
TRACE[11-04|10:56:31.601] Broadcast transaction                    hash=46e319…575833 recipients=6
TRACE[11-04|10:56:31.601] Broadcast transactions                   id=c75f7dcb9fd6063f conn=inbound    count=1
TRACE[11-04|10:56:31.601] Broadcast transactions                   id=c39143f98d04e97b conn=inbound    count=1
TRACE[11-04|10:56:31.601] Broadcast transactions                   id=3cb4aaea0f49f73c conn=inbound    count=1
TRACE[11-04|10:56:31.601] Broadcast transactions                   id=ab62dd7df5863a5f conn=inbound    count=1
TRACE[11-04|10:56:31.601] Broadcast transactions                   id=f06c06f1e958cb2e conn=inbound    count=1
TRACE[11-04|10:56:31.601] Broadcast transactions                   id=995dbe18829f1aff conn=inbound    count=1
INFO [11-04|10:56:31.632] QUORUM-CHECKPOINT                        name=TX-ACCEPTED                                                       tx=0x46e31931d3cc3076a897e9b92685e91646d9c20a37e551c60281db2faa575833
INFO [11-04|10:56:31.633] VM returned with error                   err="evm: execution reverted"
DEBUG[11-04|10:56:31.634] Trie cache stats after commit            misses=0 unloads=0
DEBUG[11-04|10:56:31.634] Trie cache stats after commit            misses=0 unloads=0
DEBUG[11-04|10:56:31.634] Trie cache stats after commit            misses=0 unloads=0
DEBUG[11-04|10:56:31.634] Persisted trie from memory database      nodes=0 size=0.00B   time=3.293µs   gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[11-04|10:56:31.635] Inserted new block                       number=10 hash=353071…ed32b0 uncles=0 txs=1 gas=64124  elapsed=2.266ms
INFO [11-04|10:56:31.635] Imported new chain segment               blocks=1 txs=1 mgas=0.064 elapsed=2.371ms mgasps=27.039 number=10 hash=353071…ed32b0 cache=12.08kB
INFO [11-04|10:56:31.635] QUORUM-CHECKPOINT                        name=BLOCK-CREATED                                                     block=353071712fddec0e7cdf74416d14b2a3d629371476b3a0afcb6a567d61ed32b0
````
nodejs:
````
[ '0xed9d02e382b34818e88B88a309c7fe71E65f419d' ]
0x064f860b6683223b03b38252853D5d2C210Cce19
1
123
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x122cf0ec031612e38b8adb69ddc53c8c6ac1d51a70c87aa28cf85378cd22d5c9",
  "blockNumber": 13,
  "contractAddress": null,
  "cumulativeGasUsed": 72228,
  "from": "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  "gasUsed": 72228,  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x064f860b6683223b03b38252853d5d2c210cce19",
  "transactionHash": "0x50f081b68a726902b9d35b34793edaf50c10b47d7f997cbb89b4838a94df7800",
  "transactionIndex": 0,
  "events": {}
}
    at /**/index.js:367:46
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x122cf0ec031612e38b8adb69ddc53c8c6ac1d51a70c87aa28cf85378cd22d5c9",
  "blockNumber": 13,
  "contractAddress": null,
  "cumulativeGasUsed": 72228,
  "from": "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  "gasUsed": 72228,  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x064f860b6683223b03b38252853d5d2c210cce19",
  "transactionHash": "0x50f081b68a726902b9d35b34793edaf50c10b47d7f997cbb89b4838a94df7800",
  "transactionIndex": 0,
  "events": {}
}
    at /**/index.js:367:46
    at process._tickCallback (internal/process/next_tick.js:68:7)
````

Contracts:
C1:
````
pragma solidity ^0.5.0;

contract C1 {
    int public x = 1;

    function setX(int _x) public {
        x = _x;
    }

    function getX() public view returns (int) {
        return x;
    }
}
````

C2:
````
pragma solidity ^0.5.0;

import { C1 } from './C1.sol';

contract C2 {
    C1 c1;
    constructor(address _c1) public {
        c1 = C1(_c1);
    }

    function setX(int _x) public {
        c1.setX(_x);
    }

    function getX() public view returns (int) {
        return c1.getX();
    }
}
````

index.js:
````
'use strict';

const web3 = require("web3");
const solc = require("solc");
const fs = require("fs");
const path = require("path");
const net = require("net");

// const w3 = new web3(new web3.providers.IpcProvider(path.resolve(__dirname, "qdata/dd1/geth.ipc"), net));
const w3 = new web3(new web3.providers.HttpProvider("http://127.0.0.1:22000"))

// compile contract
const contracts = {
    'C1.sol': {
        content: fs.readFileSync(__dirname + "/C1.sol", "utf-8")
    },
    'C2.sol': {
        content: fs.readFileSync(__dirname + "/C2.sol", "utf-8")
    }
}

const input = {
    language: 'Solidity',
    sources: contracts,
    settings: {
        optimizer: {
            enabled: false
        },
        outputSelection: {
            '*': {
                '*': ["abi", "evm.bytecode"]
            }
        }
    }
}

const parsedOutput = JSON.parse(solc.compile(JSON.stringify(input)));

const compiled = {};
for (let contract in contracts) {
    const name = contract.split(".")[0];
    const output = {};
    output.abi = parsedOutput.contracts[contract][name].abi;
    output.bin = parsedOutput.contracts[contract][name].evm.bytecode.object;
    compiled[name] = output;
}

// console.log(compiled);

// deploy contract

const init = async () => {
    const addresses = await w3.eth.getAccounts();
    console.log(addresses);

    const sendObj = {
        from: addresses[0],
        gas: 450000000
    };
    const callObj = {
        from: addresses[0]
    }

    // deploy C1
    const ct1 = new w3.eth.Contract(compiled["C1"].abi);
    ct1.options.data = "0x" + compiled["C1"].bin;
    const ct1Deployed = await ct1.deploy().send(sendObj);
    console.log(ct1Deployed.options.address);

    const newCt1 = new w3.eth.Contract(compiled["C1"].abi, ct1Deployed.options.address);

    console.log(await newCt1.methods.getX().call(callObj));
    await newCt1.methods.setX(123).send(sendObj);
    console.log(await newCt1.methods.getX().call(callObj));

    // deploy C2
    const ct2 = new w3.eth.Contract(compiled["C2"].abi);
    ct2.options.data = "0x" + compiled["C2"].bin;
    const ct2Deployed = await ct2.deploy({ arguments: [ct1Deployed.options.address] }).send(sendObj);
    console.log(ct2Deployed.options.address);

    const newCt2 = new w3.eth.Contract(compiled["C2"].abi, ct2Deployed.options.address);

    console.log(await newCt2.methods.getX().call(callObj));
    // await newCt2.methods.setX(123).send(sendObj);
    // console.log(await newCt2.methods.getX().call(callObj));
}

init();
````

**Comment by zzy96** [comment]
Hi @aditya-skeps,

Running the script on ganache-cli gives the same error. Deploying these two contracts from truffle and Quorum geth console works fine.

By looking at the error message. The reverted transaction is sending to "0x064f860b6683223b03b38252853d5d2c210cce19". This is abnormal. A contract deployment transaction should be sent to zero address. My guess is the `to` transaction field is not cleared properly in web3.js package. Please raise it to https://github.com/ethereum/web3.js/issues as this looks to be a web3.js issue.

**Comment by aditya-skeps** [comment]
I can ask there but thing is we're using web3 version beta.35 and they'll most probably just ask me to go to the latest version which I can't do at the moment.

Also, why is this issue only while deploying a contract which is importing another contract. I have been using web3 version beta.35 for more than a year now without seeing this issue up till now.

**Comment by vsmk98** [comment]
Hi @aditya-skeps, I am closing this issue as it is not a Quorum specific issue.

**Comment by fixanoid** [comment]
There's no reason not to upgrade to latest web3 version. We have tested and
support v1.2.x.
