### ISSUE TITLE
[Quorum][Raft] Out of memory - geth stuck in recursive call

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#917]
Geth version: `geth version`

OS & Version: Windows/Linux/OSX
Geth
Version: 1.8.18-stable
Quorum Version: 2.4.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

Branch, Commit Hash or Release: 
Error was encountered on 2.3 (went to 2.2.3/2.2.5/2.4 to bring the env up)

#### Expected [behaviour]
The node should be able to remain healthy

#### Actual [behaviour]
1. The node does not remain healthy
2. We have seen docker stats on the container and see an exponential spike in memory and cpu utilisation until is reaches it limit and kills itself
3. We started with 2.5 gb of memory to geth, proceeded to 4.5 gb with container having 8gb memory in total and it still fails

#### Steps to reproduce the behaviour
1. 7 node cluster running with raft consensus
2. We run tests per deployment on that envs (on an average 2000 block per deployment)
3. We saw this issue on the node which has the most data (16gb) and on which most of the transactions are performed on.

Geth arguments : 
```
PRIVATE_CONFIG=/data/privacy_manager.ipc nohup /usr/local/bin/geth \
    --datadir ${QUORUM_DIR} \
    --permissioned \
    --raft \
    --rpc \
    --rpcaddr 0.0.0.0 \
    --rpccorsdomain "*" \
    --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
    --emitcheckpoints \
    --raftport 50401 \
    --rpcport 22000 \
    --port 21000 \
    --verbosity ${VERBOSITY} \
    --maxpeers 100 \
    --nodiscover \
    --gcmode archive \
    --rpcvhosts '*'
```

Genesis.json

```
{
  "alloc": {

  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "chainId": 2018,
    "byzantiumBlock": 1,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "isQuorum":true
  },
  "difficulty": "0x0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x174876E800",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}

```

#### Backtrace

````
TRACE[12-18|15:37:09.849] Accepted connection                      addr=10.0.2.229:29526
TRACE[12-18|15:37:09.849] Failed RLPx handshake                    addr=10.0.2.229:29526      conn=inbound    err=EOF
2019-12-18 15:37:09,850 DEBG 'geth' stdout output:
TRACE[12-18|15:37:09.849] Setting up connection failed             addr=10.0.2.229:29526      err=EOF
2019-12-18 15:37:10,427 DEBG 'geth' stdout output:
TRACE[12-18|15:37:10.426] Accepted connection                      addr=10.0.0.139:62082
TRACE[12-18|15:37:10.426] Failed RLPx handshake                    addr=10.0.0.139:62082      conn=inbound    err=EOF
2019-12-18 15:37:10,427 DEBG 'geth' stdout output:
TRACE[12-18|15:37:10.427] Setting up connection failed             addr=10.0.0.139:62082      err=EOF
2019-12-18 15:37:13,682 DEBG 'geth' stdout output:
DEBUG[12-18|15:37:13.682] Recalculated downloader QoS values       rtt=20s confidence=0.948 ttl=1m0s
2019-12-18 15:37:33,687 DEBG 'geth' stdout output:
DEBUG[12-18|15:37:33.683] Recalculated downloader QoS values       rtt=20s confidence=0.974 ttl=1m0s
2019-12-18 15:37:33,723 DEBG 'geth' stdout output:
fatal error: runtime: out of memory
2019-12-18 15:37:33,734 DEBG 'geth' stdout output:
runtime stack:
runtime.throw(0x11c0fa5, 0x16)
	/usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc4ead40000, 0x9b60000, 0xc4201b9200, 0x1f41fb8)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x1f28500, 0x9b60000, 0x7f6c1d1cc1d0)
	/usr/local/go/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x1f28500, 0x4dad, 0x0)
	/usr/local/go/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x1f28500, 0x4dad, 0x1f41fc8, 0x7f6c1dd76bb0)
	/usr/local/go/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x1f28500, 0x4dad, 0x7f6c203f0101, 0x429bec)
	/usr/local/go/src/runtime/mheap.go:666 +0x118
2019-12-18 15:37:33,748 DEBG 'geth' stdout output:
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7f6c203f7970)
	/usr/local/go/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x1f28500, 0x4dad, 0x7f6c20010101, 0x429254)
	/usr/local/go/src/runtime/mheap.go:732 +0xa1
runtime.largeAlloc(0x9b5943b, 0x7f6c20670101, 0xc4c4f8660e)
	/usr/local/go/src/runtime/malloc.go:827 +0x98
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:722 +0x46
runtime.systemstack(0xc42002a000)
	/usr/local/go/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1135
goroutine 456 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:298 fp=0xc4386611b0 sp=0xc4386611a8 pc=0x46f160
runtime.mallocgc(0x9b5943b, 0xfd5860, 0xc438661201, 0x458bf7)
	/usr/local/go/src/runtime/malloc.go:721 +0x7ae fp=0xc438661258 sp=0xc4386611b0 pc=0x4258ce
runtime.makeslice(0xfd5860, 0x9b5943b, 0x9b5943b, 0xe00dc8e0e70, 0x2, 0x8)
	/usr/local/go/src/runtime/slice.go:54 +0x77 fp=0xc438661288 sp=0xc438661258 pc=0x458917
bytes.makeSlice(0x9b5943b, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:231 +0x77 fp=0xc4386612c8 sp=0xc438661288 pc=0x4f6927
bytes.(*Buffer).grow(0xc4c9cc0160, 0x144d, 0x5522)
	/usr/local/go/src/bytes/buffer.go:133 +0x140 fp=0xc438661320 sp=0xc4386612c8 pc=0x4f61b0
bytes.(*Buffer).Write(0xc4c9cc0160, 0xc4c54b8800, 0x144d, 0x154a, 0xc9cb6e35162906e9, 0x84207ee56ccfbfc3, 0x1)
	/usr/local/go/src/bytes/buffer.go:163 +0xdd fp=0xc438661350 sp=0xc438661320 pc=0x4f646d
encoding/json.compact(0xc4c9cc0160, 0xc4c54b8800, 0x144d, 0x154a, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/indent.go:55 +0x414 fp=0xc4386613c8 sp=0xc438661350 pc=0x5720e4
encoding/json.marshalerEncoder(0xc4c9cc0160, 0x107d820, 0xc4cd628fc8, 0x196, 0x1070100)
	/usr/local/go/src/encoding/json/encode.go:446 +0x1d4 fp=0xc438661438 sp=0xc4386613c8 pc=0x56b664
encoding/json.(*arrayEncoder).encode(0xc46e306d30, 0xc4c9cc0160, 0xfb4a00, 0xc421645748, 0x97, 0xfb0100)
	/usr/local/go/src/encoding/json/encode.go:759 +0xdc fp=0xc438661490 sp=0xc438661438 pc=0x56e0ec
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc4c9cc0160, 0xfb4a00, 0xc421645748, 0x97, 0x100)
	/usr/local/go/src/encoding/json/encode.go:766 +0x64 fp=0xc4386614d0 sp=0xc438661490 pc=0x5786e4
encoding/json.(*sliceEncoder).encode(0xc46e306d38, 0xc4c9cc0160, 0xfb4a00, 0xc421645748, 0x97, 0xfb0100)
	/usr/local/go/src/encoding/json/encode.go:733 +0xc1 fp=0xc438661510 sp=0xc4386614d0 pc=0x56ddf1
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc4c9cc0160, 0xfb4a00, 0xc421645748, 0x97, 0xc421640100)
	/usr/local/go/src/encoding/json/encode.go:745 +0x64 fp=0xc438661550 sp=0xc438661510 pc=0x578664
encoding/json.(*encodeState).reflectValue(0xc4c9cc0160, 0xfb4a00, 0xc421645748, 0x97, 0xc421640100)
	/usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc438661588 sp=0xc438661550 pc=0x56abf2
encoding/json.interfaceEncoder(0xc4c9cc0160, 0x10175a0, 0xc469ba24a0, 0x194, 0x100)
	/usr/local/go/src/encoding/json/encode.go:609 +0xdb fp=0xc4386615c8 sp=0xc438661588 pc=0x56cb3b
encoding/json.(*structEncoder).encode(0xc427283260, 0xc4c9cc0160, 0x10bb0e0, 0xc469ba2480, 0x199, 0xf90100)
	/usr/local/go/src/encoding/json/encode.go:637 +0x255 fp=0xc438661728 sp=0xc4386615c8 pc=0x56ce85
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4c9cc0160, 0x10bb0e0, 0xc469ba2480, 0x199, 0xc469ba0100)
	/usr/local/go/src/encoding/json/encode.go:651 +0x64 fp=0xc438661768 sp=0xc438661728 pc=0x578564
encoding/json.(*ptrEncoder).encode(0xc4202173d0, 0xc4c9cc0160, 0xf95480, 0xc469ba2480, 0x16, 0xf90100)
	/usr/local/go/src/encoding/json/encode.go:778 +0xe3 fp=0xc4386617a8 sp=0xc438661768 pc=0x56e353
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4c9cc0160, 0xf95480, 0xc469ba2480, 0x16, 0xc469ba0100)
	/usr/local/go/src/encoding/json/encode.go:783 +0x64 fp=0xc4386617e8 sp=0xc4386617a8 pc=0x578764
encoding/json.(*encodeState).reflectValue(0xc4c9cc0160, 0xf95480, 0xc469ba2480, 0x16, 0x100)
	/usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc438661820 sp=0xc4386617e8 pc=0x56abf2
encoding/json.(*encodeState).marshal(0xc4c9cc0160, 0xf95480, 0xc469ba2480, 0xc438660100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:296 +0xaf fp=0xc438661858 sp=0xc438661820 pc=0x56a8df
encoding/json.(*Encoder).Encode(0xc421645630, 0xf95480, 0xc469ba2480, 0xc438661938, 0xc4215c0860)
	/usr/local/go/src/encoding/json/stream.go:193 +0x96 fp=0xc4386618f8 sp=0xc438661858 pc=0x575e16
encoding/json.(*Encoder).Encode-fm(0xf95480, 0xc469ba2480, 0xc4216456a8, 0x0)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/json.go:118 +0x3e fp=0xc438661930 sp=0xc4386618f8 pc=0x9282ae
github.com/ethereum/go-ethereum/rpc.(*jsonCodec).Write(0xc421645680, 0xf95480, 0xc469ba2480, 0x0, 0x0)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/json.go:349 +0x93 fp=0xc438661968 sp=0xc438661930 pc=0x91d6f3
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc427266510, 0x1b9e100, 0xc420440ec0, 0x1ba3620, 0xc421645680, 0xc421613f20)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:337 +0xa4 fp=0xc4386619d8 sp=0xc438661968 pc=0x920724
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc427266510, 0x1b9e1c0, 0xc427283440, 0x1ba3620, 0xc421645680, 0x11b5201, 0x1, 0x0, 0x0)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:192 +0x37d fp=0xc438661b28 sp=0xc4386619d8 pc=0x91e6ed
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc427266510, 0x1b9e1c0, 0xc427283440, 0x1ba3620, 0xc421645680, 0x1)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:223 +0x65 fp=0xc438661b80 sp=0xc438661b28 pc=0x91f075
github.com/ethereum/go-ethereum/rpc.(*Server).ServeHTTP(0xc427266510, 0x1b9ca40, 0xc4216eddc0, 0xc42704cc00)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:253 +0x4c2 fp=0xc438661c38 sp=0xc438661b80 pc=0x918722
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1b9ca40, 0xc4216eddc0, 0xc42704cc00)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rs/cors/cors.go:190 +0x108 fp=0xc438661c90 sp=0xc438661c38 pc=0x9060d8
net/http.HandlerFunc.ServeHTTP(0xc42010e880, 0x1b9ca40, 0xc4216eddc0, 0xc42704cc00)
	/usr/local/go/src/net/http/server.go:1918 +0x44 fp=0xc438661cb8 sp=0xc438661c90 pc=0x85ab34
github.com/ethereum/go-ethereum/rpc.(*virtualHostHandler).ServeHTTP(0xc42010e8c0, 0x1b9ca40, 0xc4216eddc0, 0xc42704cc00)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:317 +0x1c9 fp=0xc438661d18 sp=0xc438661cb8 pc=0x9190d9
net/http.serverHandler.ServeHTTP(0xc4272751e0, 0x1b9ca40, 0xc4216eddc0, 0xc42704cc00)
	/usr/local/go/src/net/http/server.go:2619 +0xb4 fp=0xc438661d48 sp=0xc438661d18 pc=0x85d924
net/http.(*conn).serve(0xc420518f00, 0x1b9e100, 0xc420440c40)
	/usr/local/go/src/net/http/server.go:1801 +0x71d fp=0xc438661fc8 sp=0xc438661d48 pc=0x859a0d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc438661fd0 sp=0xc438661fc8 pc=0x471d91
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
goroutine 1 [chan receive, 1 minutes]:
github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc42025cc80)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:467 +0x7f
main.geth(0xc4200b0160, 0x0, 0x0)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:280 +0x138
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xff18c0, 0x1255e80, 0xc4200b0160, 0xc4200b0160, 0xc4204eff40)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42022a1a0, 0xc420010200, 0x20, 0x20, 0x0, 0x0)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x635
main.main()
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:261 +0x55
goroutine 6 [chan receive, 1 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc4200663c0, 0xc420066300)
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xc0
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/go/quorum-2.3.0/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x149
goroutine 7 [chan receive, 1 minutes]:
````

**Comment by jbhurat** [comment]
Hi @preetgsanand, I have been trying to reproduce the above issue by creating about 100,000 blocks and restarting the network, but so far no luck. Is it possible to share more details about the contracts and transactions that were sent, so that it is easier to reproduce.

**Comment by jbhurat** [comment]
Closing the issue as there is no activity. Please reopen or create a new issue if you need any further assistance.
