### ISSUE TITLE
Oraclize/Provable is not working with quorum nodes.

### ISSUE THREAD

**Issue by grseetha** [Consensys-Incorporated/quorum#962]
Trying to implement Oraclize/Provable in solidity smart contract. When I test with plain ethereum it is working as expected.

When I deployed in Quorum network and trying to access the function which utilizes Oraclize api it is failing with below issue

The smart contract used: **https://docs.provable.xyz/#ethereum-quick-start**

#### System information

Version: 1.8.18-stable
Git Commit: b5266cbd194aaa61efd1815df87c7d9edaad118c
Quorum Version: 2.4.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.13.8
Operating System: darwin
GOPATH=
GOROOT=/usr/local/go

#### Expected behaviour
Invoking the Oraclize based smart contract function should be successful

#### Actual behaviour
It is failing with below error.

Error: Transaction: 0x49d37a47060dd66a5c73994a84b86c0dd86366868b84998f6635c2c4551e78b7 exited with an error (status 0). \n     Please check that the transaction:\n     - satisfies all conditions set by Solidity `require` statements.\n     - does not trigger a Solidity `revert` statement.\n\n

#### Steps to reproduce the behaviour
1. Create a quorum truffle project
2. Create the smart contract with Oraclize
3. Deploy using the truffle command
4. Try to call the function from the truffle console.

#### Backtrace

````
Thrown:
{ Error: Transaction: 0xba5b5a771fbcd0c8d95667cfed1442346c17345fcb1a2c2de3a3fef598bd6558 exited with an error (status 0).     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
    at TruffleContract.updatePrice (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
    at evalmachine.<anonymous>:0:6
    at sigintHandlersWrap (vm.js:288:15)
    at Script.runInContext (vm.js:130:14)
    at runScript (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:222:1)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:237:1)
    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/repl.js:131:1)
    at bound (domain.js:402:14)
    at REPLServer.runBound [as eval] (domain.js:415:12)
    at REPLServer.onLine (repl.js:642:10)
    at REPLServer.emit (events.js:198:13)
    at REPLServer.EventEmitter.emit (domain.js:448:20)
    at REPLServer.Interface._onLine (readline.js:308:10)
    at REPLServer.Interface._line (readline.js:656:8)
    at REPLServer.Interface._ttyWrite (readline.js:937:14)
    at REPLServer.self._ttyWrite (repl.js:715:7)
    at ReadStream.onkeypress (readline.js:184:10)
    at ReadStream.emit (events.js:198:13)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1073:36)
    at ReadStream.emit (events.js:198:13)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadStream.Readable.push (_stream_readable.js:224:10)
  message:
   'Transaction: 0xba5b5a771fbcd0c8d95667cfed1442346c17345fcb1a2c2de3a3fef598bd6558 exited with an error (status 0). \n     Please check that the transaction:\n     - satisfies all conditions set by Solidity `require` statements.\n     - does not trigger a Solidity `revert` statement.\n',
  stack:
   'Error: Transaction: 0xba5b5a771fbcd0c8d95667cfed1442346c17345fcb1a2c2de3a3fef598bd6558 exited with an error (status 0).     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)\n    at TruffleContract.updatePrice (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)\n    at evalmachine.<anonymous>:0:6\n    at sigintHandlersWrap (vm.js:288:15)\n    at Script.runInContext (vm.js:130:14)\n    at runScript (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:222:1)\n    at Console.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:237:1)\n    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/repl.js:131:1)\n    at bound (domain.js:402:14)\n    at REPLServer.runBound [as eval] (domain.js:415:12)\n    at REPLServer.onLine (repl.js:642:10)\n    at REPLServer.emit (events.js:198:13)\n    at REPLServer.EventEmitter.emit (domain.js:448:20)\n    at REPLServer.Interface._onLine (readline.js:308:10)\n    at REPLServer.Interface._line (readline.js:656:8)\n    at REPLServer.Interface._ttyWrite (readline.js:937:14)\n    at REPLServer.self._ttyWrite (repl.js:715:7)\n    at ReadStream.onkeypress (readline.js:184:10)\n    at ReadStream.emit (events.js:198:13)\n    at ReadStream.EventEmitter.emit (domain.js:448:20)\n    at emitKeys (internal/readline.js:424:14)\n    at emitKeys.next (<anonymous>)\n    at ReadStream.onData (readline.js:1073:36)\n    at ReadStream.emit (events.js:198:13)\n    at ReadStream.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at ReadStream.Readable.push (_stream_readable.js:224:10)',
  name: 'StatusError',
  tx:
   '0xba5b5a771fbcd0c8d95667cfed1442346c17345fcb1a2c2de3a3fef598bd6558',
  receipt:
   { blockHash:
      '0xefbe098a66574b2636f7a0c3dd1e7866c1d833f763ad9e90dfb7c38c9a143227',
     blockNumber: 18,
     contractAddress: null,
     cumulativeGasUsed: 31085,
     from: '0xeb6ab3eb567c9474018f2297d748a34feaa6f9c2',
     gasUsed: 31085,
     logs: [],
     logsBloom:
      '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
     status: false,
     to: '0x6c3c75264990939ec0d58bd4c39d47ee0eb709f8',
     transactionHash:
      '0xba5b5a771fbcd0c8d95667cfed1442346c17345fcb1a2c2de3a3fef598bd6558',
     transactionIndex: 0,
     rawLogs: [] },
  reason: undefined,
  hijackedStack:
   'Error: Transaction: 0xba5b5a771fbcd0c8d95667cfed1442346c17345fcb1a2c2de3a3fef598bd6558 exited with an error (status 0). \n     Please check that the transaction:\n     - satisfies all conditions set by Solidity `require` statements.\n     - does not trigger a Solidity `revert` statement.\n\n    at StatusError.ExtendableError (/usr/local/lib/node_modules/truffle/build/webpack:/packages/error/index.js:10:1)\n    at new StatusError (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/statuserror.js:33:1)\n    at Object.receipt (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/handlers.js:124:1)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
````

**Comment by fixanoid** [comment]
@grsind19 can you share the genesis you've used to prime the chain? Also, was there anything in the quorum nodes log for the error?

**Comment by grseetha** [comment]
> @grsind19 can you share the genesis you've used to prime the chain? Also, was there anything in the quorum nodes log for the error?

I think the issue is with ethereum bridge. For any private network of quorum we need to run the ethereum bridge connector to make the Oraclize work in Quorum network.

We can close this issue.
