### ISSUE TITLE
web3.eth.sendRawPrivateTransaction is not a function

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#993]
Hi,

I am getting error function not found while executing sendRawPrivateTransaction in JS file for submitting transaction.

System information
Geth version: 
```
Version: 1.8.18-stable
Git Commit: 685f59f
Quorum Version: 2.5.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.11.13
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.11.13.linux.amd64
```

OS & Version: OSX

Branch, Commit Hash or Release: git status

#######My smart contract code:

```
pragma solidity ^0.5.0;

contract Meme {
string memeHash;

constructor(string memory _initVal) public {
memeHash = _initVal;
}

function set(string memory _memeHash) public {
memeHash = _memeHash;
}

function get() public view returns (string memory) {
return memeHash;
}
}
```

My app.js file code through which I am trying to submit the private transactions from node1 to node7 (I am using quorum 7 node sample network on vagrant)
```
const Tx = require('ethereumjs-tx')
const Web3 = require('web3')
const web3 = new Web3('http://localhost:22000')

const account1 = '0xed9d02e382b34818e88B88a309c7fe71E65f419d'

const privateKey1= Buffer.from('E.........................................F1','hex')

const contractAddress = '0x9AC8A5eFC282aFab3B2a7286704F232767645733'
const ABI = [{"constant":false,"inputs":[{"name":"_memeHash","type":"string"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_initVal","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]

const contract = web3.eth.Contract(ABI, contractAddress)

const data = contract.methods.set('QmWTVJgoPXfmJodjMtgZQ9f2vjGQM2HDFsVSUMzxwzkzj7').encodeABI()

web3.eth.getTransactionCount(account1, (err, txCount) => {

console.log ('txCount: ',txCount)

//Build the transaction
const txObject = {
    nounce: web3.utils.toHex(txCount),
    gasLimit: web3.utils.toHex(800000),
    gasPrice: web3.utils.toHex(web3.utils.toWei('0','gwei')),
    to: contractAddress,
    value: '0x00',
    data: data
}

//Sing the transaction
const tx = new Tx(txObject)
tx.sign(privateKey1);
const serializedTransaction = tx.serialize()
const raw = '0x' + serializedTransaction.toString('hex')

//Broadcast the transaction
web3.eth.sendRawPrivateTransaction(raw, {privateFor: ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]}, function(err, hash) {
    if (!err)
      console.log(hash); 
    else
      console.log(err);
  });
})
```

Expected behaviour
Transaction should be processed successfully and value should be updated on node1, node7 only.

Actual behaviour
Getting function not found error.
```
(node:4982) UnhandledPromiseRejectionWarning: TypeError: **web3.eth.sendRawPrivateTransaction is not a function**
    at GetTransactionCountMethod.<anonymous> (/Users/arjungupta/workdir/Quorum/memecompleteQ/src/components/AppQuorum.js:37:14)
    at GetTransactionCountMethod._callee$ (/Users/arjungupta/workdir/Quorum/memecompleteQ/node_modules/web3-core-method/dist/web3-core-method.cjs.js:126:22)
    at tryCatch (/Users/arjungupta/workdir/Quorum/memecompleteQ/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/arjungupta/workdir/Quorum/memecompleteQ/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as throw] (/Users/arjungupta/workdir/Quorum/memecompleteQ/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/arjungupta/workdir/Quorum/memecompleteQ/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (/Users/arjungupta/workdir/Quorum/memecompleteQ/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Steps to reproduce the behaviour
http://docs.goquorum.com/en/latest/Getting%20Started/api/

**If possible, please share latest example of connecting and submitting transactions using API so I can connect UI.**

**Comment by fixanoid** [comment]
@mrarjunbgupta what version of web3 are you using? AFAIK, sendRawPrivateTransaction isnt part of unpatched web3, so you'd need to use something like quorum.js: https://github.com/jpmorganchase/quorum.js

**Comment by ghost** [comment]
@fixanoid 
I am getting multiple errors while submitting update transaction from UI i.e. I am able invoke get function to get the value but set function is failing from UI because of privateFor parameter (differs from ethereum). I have tried with VAGRANT and LOCAL Quorum version but didn't get success.

**Do you have any sample code which invokes set function from JS file using quorum-js or web3 etc which can be integrated to an UI? If yes, please share.**

Code using quorum-js as suggested above
```
const Tx =  require('ethereumjs-tx') 
const Web3 = require('web3')

const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:22001"))
const quorumjs = require("quorum-js");

const enclaveOptions = {
  /* at least one enclave option must be provided     */
  /* ipcPath is preferred for utilizing older API     */
  /* Constellation only supports ipcPath              */
  /* For Tessera: privateUrl is ThirdParty server url */
  //ipcPath: "/Users/arjungupta/workdir/Quorum/quorum-examples/examples/7nodes/qdata/c1/tm.ipc",
  publicUrl: "http://localhost:8080",
  privateUrl: "http://localhost:8090"
};
console.log ('16');

const txnManager = quorumjs.RawTransactionManager(web3, enclaveOptions);

// Account
const account1 = '0xed9d02e382b34818e88B88a309c7fe71E65f419d'
const privateKey1= Buffer.from('E6.....................F1','hex')

//getting contract object
const contractAddress = '0x7B3cF504af1cFa2239AF8712045d4D7066e38ABc'
const ABI = [{"constant":false,"inputs":[{"name":"_memeHash","type":"string"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_initVal","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]
const contract = web3.eth.Contract(ABI, contractAddress)

const data = contract.methods.set('QmWTVJgoPXfmJodjMtgZQ9f2vjGQM2HDFsVSUMzxwzkzj7').encodeABI()

console.log ('31');

//Build the transaction
const txObject = {
      gasPrice: 0,
      gasLimit: 4300000,
      to: contractAddress,
      from: account1,
      data: data,
      isPrivate: true,
      privateFrom: 'BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo=',
      privateFor: 'ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc='
  }

  console.log ('45');

  txnManager.sendRawTransaction(txObject);
  
```

Error message on console:

```
MacBook-Pro components % node AppQuorum1.js
16
31
45
(node:10079) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 127.0.0.1:8090
    at new RequestError (/Users/arjungupta/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/arjungupta/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/arjungupta/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/arjungupta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.onRequestError (/Users/arjungupta/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
(node:10079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fixanoid** [comment]
@mrarjunbgupta quorum.js has a 7node tester bundled. Please see here: https://github.com/jpmorganchase/quorum.js/tree/master/7nodes-test quorum-examples also has tester bundled, please see here: https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes/samples

Finally, the error you are getting is connection refused for localhost:8090 which is supposed to be Tessera's 3rd party server. Either your Tessera is not up, or its not configured correctly.

**Comment by ghost** [comment]
@fixanoid 

**I have used below file but it is giving error:**
https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/samples/send-private-txn-quorum.js/send.js


**Error:**
```
MacBook-Pro send-private-txn-quorum.js % node send.js
Memory limit exceeded for Node's built-in crypto.scrypt, falling back to scryptsy (times: 1), if this happens frequently you can improve the performance of scrypt when running Node.js versions older than 12.0.0 by installing the (deprecated) scrypt package in your project
(node:17464) UnhandledPromiseRejectionWarning: Error: Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: 
    at Object.exports.toBuffer (/Users/arjungupta/node_modules/ethereumjs-util/dist/bytes.js:79:23)
    at Transaction.setter [as to] (/Users/arjungupta/node_modules/ethereumjs-util/dist/object.js:42:25)
    at /Users/arjungupta/node_modules/ethereumjs-util/dist/object.js:95:38
    at Array.forEach (<anonymous>)
    at Object.exports.defineProperties (/Users/arjungupta/node_modules/ethereumjs-util/dist/object.js:93:20)
    at new Transaction (/Users/arjungupta/node_modules/ethereumjs-tx/dist/transaction.js:127:27)
    at serializeSignedTransaction (/Users/arjungupta/node_modules/quorum-js/lib/rawTransactionManager.js:61:16)
    at /Users/arjungupta/node_modules/quorum-js/lib/rawTransactionManager.js:176:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**I have also tried below file but still getting error:**
   https://github.com/jpmorganchase/quorum.js/blob/master/7nodes-test/deployContractViaHttp.js

**Error:**
```
MacBook-Pro 7nodes-test % node deployContractViaHttp.js
Memory limit exceeded for Node's built-in crypto.scrypt, falling back to scryptsy (times: 1), if this happens frequently you can improve the performance of scrypt when running Node.js versions older than 12.0.0 by installing the (deprecated) scrypt package in your project
Error: Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: 
    at Object.exports.toBuffer (/Users/arjungupta/node_modules/ethereumjs-util/dist/bytes.js:79:23)
    at Transaction.setter [as to] (/Users/arjungupta/node_modules/ethereumjs-util/dist/object.js:42:25)
    at /Users/arjungupta/node_modules/ethereumjs-util/dist/object.js:95:38
    at Array.forEach (<anonymous>)
    at Object.exports.defineProperties (/Users/arjungupta/node_modules/ethereumjs-util/dist/object.js:93:20)
    at new Transaction (/Users/arjungupta/node_modules/ethereumjs-tx/dist/transaction.js:127:27)
    at serializeSignedTransaction (/Users/arjungupta/workdir/Quorum/quorum.js/lib/rawTransactionManager.js:61:16)
    at /Users/arjungupta/workdir/Quorum/quorum.js/lib/rawTransactionManager.js:176:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```


**I am using node v12.16.1.**
